from enum import IntEnum, StrEnum


class DayOfWeek(IntEnum):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7


class TermType(StrEnum):
    WINTER = "WINTER"
    SUMMER = "SUMMER"


class CourseType(StrEnum):
    MANDATORY = "MANDATORY"
    ELECTIVE = "ELECTIVE"


class AcademicTitle(StrEnum):
    FULL_PROFESSOR = "FULL_PROFESSOR"
    ASSOCIATE_PROFESSOR = "ASSOCIATE_PROFESSOR"
    ASSISTANT_PROFESSOR = "ASSISTANT_PROFESSOR"
    ASSISTANT = "ASSISTANT"
    OTHER = "OTHER"


class StaffType(StrEnum):
    INTERNAL = "INTERNAL"
    ENGAGED = "ENGAGED"
    OTHER_UP_FACULTY = "OTHER_UP_FACULTY"
    EXTERNAL = "EXTERNAL"


class AvailabilityType(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    PREFERRED = "PREFERRED"
    AVOID = "AVOID"


class StudentGroupType(StrEnum):
    COHORT = "COHORT"
    LECTURE_GROUP = "LECTURE_GROUP"
    NUMERICAL_GROUP = "NUMERICAL_GROUP"
    LAB_GROUP = "LAB_GROUP"


class RoomType(StrEnum):
    GENERAL_ROOM = "GENERAL_ROOM"
    LABORATORY = "LABORATORY"


class RoomStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    MAINTENANCE = "MAINTENANCE"


class CourseOfferingStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class ComponentType(StrEnum):
    LECTURE = "LECTURE"
    NUMERICAL = "NUMERICAL"
    LABORATORY = "LABORATORY"


class TeachingRole(StrEnum):
    LECTURER = "LECTURER"
    NUMERICAL_INSTRUCTOR = "NUMERICAL_INSTRUCTOR"
    LAB_INSTRUCTOR = "LAB_INSTRUCTOR"


class TimeConstraintType(StrEnum):
    ALLOWED_WINDOW = "ALLOWED_WINDOW"
    FORBIDDEN_WINDOW = "FORBIDDEN_WINDOW"
    PREFERRED_WINDOW = "PREFERRED_WINDOW"
    FIXED_WINDOW = "FIXED_WINDOW"


class DependencyType(StrEnum):
    PRECEDES = "PRECEDES"
    SAME_DAY = "SAME_DAY"
    DIFFERENT_DAY = "DIFFERENT_DAY"
    CONSECUTIVE = "CONSECUTIVE"


class TimetableSourceType(StrEnum):
    GENERATED = "GENERATED"
    MANUAL = "MANUAL"
    IMPORTED = "IMPORTED"
    REOPTIMIZED = "REOPTIMIZED"


class SchedulingAlgorithm(StrEnum):
    FIRST_FIT_DECREASING = "FIRST_FIT_DECREASING"
    BEST_FIT_DECREASING = "BEST_FIT_DECREASING"
    CP_SAT = "CP_SAT"
    HYBRID = "HYBRID"


class TimetableRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    INFEASIBLE = "INFEASIBLE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AssignmentSource(StrEnum):
    SOLVER = "SOLVER"
    MANUAL = "MANUAL"
    IMPORTED = "IMPORTED"
    PRESERVED = "PRESERVED"
