
from __future__ import annotations

# key, first name, last name, academic title, staff type
STAFF_SPECS = [
    ('blerim-rexha', 'Blerim', 'Rexha', 'FULL_PROFESSOR', 'INTERNAL'),
    ('bujar-krasniqi', 'Bujar', 'Krasniqi', 'FULL_PROFESSOR', 'INTERNAL'),
    ('enver-hamiti', 'Enver', 'Hamiti', 'FULL_PROFESSOR', 'INTERNAL'),
    ('isak-shabani', 'Isak', 'Shabani', 'FULL_PROFESSOR', 'INTERNAL'),
    ('kadri-sylejmani', 'Kadri', 'Sylejmani', 'FULL_PROFESSOR', 'INTERNAL'),
    ('milaim-zabeli', 'Milaim', 'Zabeli', 'FULL_PROFESSOR', 'INTERNAL'),
    ('mimoza-ibrani', 'Mimoza', 'Ibrani', 'FULL_PROFESSOR', 'INTERNAL'),
    ('qamil-kabashi', 'Qamil', 'Kabashi', 'FULL_PROFESSOR', 'INTERNAL'),
    ('sabrije-osmanaj', 'Sabrije', 'Osmanaj', 'FULL_PROFESSOR', 'INTERNAL'),
    ('arben-gjukaj', 'Arben', 'Gjukaj', 'ASSOCIATE_PROFESSOR', 'INTERNAL'),
    ('hena-maloku-berzati', 'Hëna', 'Maloku Berzati', 'ASSOCIATE_PROFESSOR', 'INTERNAL'),
    ('shqipe-lohaj', 'Shqipe', 'Lohaj', 'ASSOCIATE_PROFESSOR', 'INTERNAL'),
    ('valdete-rexhebeqaj-hamiti', 'Valdete', 'Rexhëbeqaj-Hamiti', 'ASSOCIATE_PROFESSOR', 'INTERNAL'),
    ('vezir-rexhepi', 'Vezir', 'Rexhepi', 'ASSOCIATE_PROFESSOR', 'INTERNAL'),
    ('zana-limani-fazliu', 'Zana', 'Limani-Fazliu', 'ASSOCIATE_PROFESSOR', 'INTERNAL'),
    ('artan-mazrekaj', 'Artan', 'Mazrekaj', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('avni-rexhepi', 'Avni', 'Rexhepi', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('besmir-sejdiu', 'Besmir', 'Sejdiu', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('dhurate-hyseni', 'Dhuratë', 'Hyseni', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('faton-maliqi', 'Faton', 'Maliqi', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('jeta-dobruna', 'Jeta', 'Dobruna', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('kadri-kadriu', 'Kadri', 'Kadriu', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('lavdim-kurtaj', 'Lavdim', 'Kurtaj', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('mergim-hoti', 'Mërgim', 'Hoti', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('nora-sadiku-dushi', 'Nora', 'Sadiku-Dushi', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('nuri-berisha', 'Nuri', 'Berisha', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('valon-veliu', 'Valon', 'Veliu', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('vjosa-shatri', 'Vjosa', 'Shatri', 'ASSISTANT_PROFESSOR', 'INTERNAL'),
    ('adrian-ymeri', 'Adrian', 'Ymeri', 'ASSISTANT', 'INTERNAL'),
    ('arben-mashkulli', 'Arben', 'Mashkulli', 'ASSISTANT', 'INTERNAL'),
    ('arbena-musa', 'Arbena', 'Musa', 'ASSISTANT', 'INTERNAL'),
    ('blend-arifaj', 'Blend', 'Arifaj', 'ASSISTANT', 'INTERNAL'),
    ('bregan-isufi', 'Bregan', 'Isufi', 'ASSISTANT', 'INTERNAL'),
    ('daline-vranovci', 'Dalinë', 'Vranovci', 'ASSISTANT', 'INTERNAL'),
    ('fatin-gota', 'Fatin', 'Gota', 'ASSISTANT', 'INTERNAL'),
    ('fatmire-hyseni', 'Fatmire', 'Hyseni', 'ASSISTANT', 'INTERNAL'),
    ('gentrit-fejza', 'Gentrit', 'Fejza', 'ASSISTANT', 'INTERNAL'),
    ('kaltrina-mustafa-lushaj', 'Kaltrina', 'Mustafa-Lushaj', 'ASSISTANT', 'INTERNAL'),
    ('labeat-arbneshi', 'Labeat', 'Arbneshi', 'ASSISTANT', 'INTERNAL'),
    ('mihrije-kadriu', 'Mihrije', 'Kadriu', 'ASSISTANT', 'INTERNAL'),
    ('nafije-shabani-dallku', 'Nafije', 'Shabani-Dallku', 'ASSISTANT', 'INTERNAL'),
    ('petrit-emini', 'Petrit', 'Emini', 'ASSISTANT', 'INTERNAL'),
    ('uran-lajci', 'Uran', 'Lajçi', 'ASSISTANT', 'INTERNAL'),
    ('vullnet-laniku', 'Vullnet', 'Laniku', 'ASSISTANT', 'INTERNAL'),
    ('yllka-kabashi', 'Yllka', 'Kabashi', 'ASSISTANT', 'INTERNAL'),
    ('admir-kadriu', 'Admir', 'Kadriu', 'OTHER', 'ENGAGED'),
    ('besnik-dragusha', 'Besnik', 'Dragusha', 'OTHER', 'ENGAGED'),
    ('betim-hoxha', 'Betim', 'Hoxha', 'OTHER', 'ENGAGED'),
    ('doruntine-berisha', 'Doruntinë', 'Berisha', 'OTHER', 'ENGAGED'),
    ('drilon-bunjaku', 'Drilon', 'Bunjaku', 'OTHER', 'ENGAGED'),
    ('enis-riza', 'Enis', 'Riza', 'OTHER', 'ENGAGED'),
    ('faruk-ahmeti', 'Faruk', 'Ahmeti', 'OTHER', 'ENGAGED'),
    ('faton-mehmeti', 'Faton', 'Mehmeti', 'OTHER', 'ENGAGED'),
    ('fatos-peci', 'Fatos', 'Peci', 'OTHER', 'ENGAGED'),
    ('fjolla-gashi', 'Fjolla', 'Gashi', 'OTHER', 'ENGAGED'),
    ('kadrije-simnica-aliu', 'Kadrije', 'Simnica-Aliu', 'OTHER', 'ENGAGED'),
    ('kujtim-mustafa', 'Kujtim', 'Mustafa', 'OTHER', 'ENGAGED'),
    ('lule-ahmedi', 'Lule', 'Ahmedi', 'OTHER', 'ENGAGED'),
    ('mendim-hajdari', 'Mendim', 'Hajdari', 'OTHER', 'ENGAGED'),
    ('miranda-kukaj', 'Miranda', 'Kukaj', 'OTHER', 'ENGAGED'),
    ('qefsere-gjonbalaj', 'Qefsere', 'Gjonbalaj', 'OTHER', 'ENGAGED'),
    ('rafet-duriqi', 'Rafet', 'Duriqi', 'OTHER', 'ENGAGED'),
    ('ramadan-plakolli', 'Ramadan', 'Plakolli', 'OTHER', 'ENGAGED'),
    ('rina-shehu-gashi', 'Rina', 'Shehu-Gashi', 'OTHER', 'ENGAGED'),
    ('rrezearta-thaqi', 'Rrezearta', 'Thaqi', 'OTHER', 'ENGAGED'),
    ('shpresa-dragusha', 'Shpresa', 'Dragusha', 'OTHER', 'ENGAGED'),
    ('uran-rakovica', 'Uran', 'Rakovica', 'OTHER', 'ENGAGED'),
    ('vigan-raca', 'Vigan', 'Raça', 'OTHER', 'ENGAGED'),
    ('visar-kajtazi', 'Visar', 'Kajtazi', 'OTHER', 'ENGAGED'),
    ('ariana-kadriu', 'Ariana', 'Kadriu', 'OTHER', 'OTHER_UP_FACULTY'),
    ('leutrim-klinaku', 'Leutrim', 'Klinaku', 'OTHER', 'OTHER_UP_FACULTY'),
    ('yllka-delija', 'Yllka', 'Delija', 'OTHER', 'OTHER_UP_FACULTY'),
    ('qefsere-doko', 'Qefsere', 'Doko', 'OTHER', 'ENGAGED'),
    ('agnese-avdiu', 'Agnesë', 'Avdiu', 'OTHER', 'ENGAGED'),
    ('astrit-syla', 'Astrit', 'Syla', 'OTHER', 'ENGAGED'),
    ('blerta-selimaj', 'Blerta', 'Selimaj', 'OTHER', 'ENGAGED'),
    ('fidan-krasniqi', 'Fidan', 'Krasniqi', 'OTHER', 'ENGAGED'),
    ('hidajete-sadiku', 'Hidajete', 'Sadiku-Ibrahimi', 'OTHER', 'ENGAGED'),
    ('rreze-halili', 'Rreze', 'Halili', 'OTHER', 'ENGAGED'),
    ('departamenti-fiek', 'Departamenti', 'FIEK', 'OTHER', 'INTERNAL'),
    ('partneret-industrise', 'Partnerët', 'e Industrisë', 'OTHER', 'EXTERNAL'),
]

# code, program semester, name, type, elective group, ECTS, L/UN/UL,
# lecturer, practical instructor, offered, requires timetable
COURSE_SPECS = [
    ('EAR-BSC-S1-C01', 'EAR-BSC-S1', 'Algjebra lineare me Kalkulus 1', 'MANDATORY', None, 7.0, 3, 3, 0, 'qefsere-doko', 'arben-mashkulli', False, True),
    ('EAR-BSC-S1-C02', 'EAR-BSC-S1', 'Fizika inxhinierike 1', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'betim-hoxha', False, True),
    ('EAR-BSC-S1-C03', 'EAR-BSC-S1', 'Bazat e inxhinierisë elektrike 1', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'uran-rakovica', False, True),
    ('EAR-BSC-S1-C04', 'EAR-BSC-S1', 'Bazat e programimit', 'MANDATORY', None, 5.0, 2, 0, 2, 'avni-rexhepi', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S1-C05', 'EAR-BSC-S1', 'Shkathtësitë e komunikimit', 'MANDATORY', None, 3.0, 2, 0, 0, 'blerim-rexha', 'faton-mehmeti', False, True),
    ('EAR-BSC-S1-C06', 'EAR-BSC-S1', 'Praktikumi në matematikë', 'ELECTIVE', 'EAR-BSC-S1-E1', 3.0, 2, 0, 0, 'departamenti-fiek', 'miranda-kukaj', False, True),
    ('EAR-BSC-S1-C07', 'EAR-BSC-S1', 'Veglat bazë softuerike', 'ELECTIVE', 'EAR-BSC-S1-E1', 3.0, 2, 0, 0, 'besmir-sejdiu', 'arben-mashkulli', False, True),
    ('EAR-BSC-S2-C01', 'EAR-BSC-S2', 'Gjeometri analitike me Kalkulus 2', 'MANDATORY', None, 7.0, 3, 3, 0, 'qefsere-doko', 'miranda-kukaj', False, True),
    ('EAR-BSC-S2-C02', 'EAR-BSC-S2', 'Fizika inxhinierike 2', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'arben-mashkulli', False, True),
    ('EAR-BSC-S2-C03', 'EAR-BSC-S2', 'Bazat e inxhinierisë elektrike 2', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'betim-hoxha', False, True),
    ('EAR-BSC-S2-C04', 'EAR-BSC-S2', 'Algoritmet dhe strukturat e të dhënave', 'MANDATORY', None, 6.0, 2, 0, 2, 'kadri-sylejmani', 'uran-rakovica', False, True),
    ('EAR-BSC-S2-C05', 'EAR-BSC-S2', 'Qarqet digjitale', 'MANDATORY', None, 6.0, 2, 1, 1, 'sabrije-osmanaj', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S3-C01', 'EAR-BSC-S3', 'Kalkulus 3 me probabilitet', 'MANDATORY', None, 5.0, 2, 2, 0, 'shqipe-lohaj', 'faton-mehmeti', False, True),
    ('EAR-BSC-S3-C02', 'EAR-BSC-S3', 'Mikroprocesorët dhe mikrokontrollerët', 'MANDATORY', None, 5.0, 2, 0, 2, 'lavdim-kurtaj', 'miranda-kukaj', False, True),
    ('EAR-BSC-S3-C03', 'EAR-BSC-S3', 'Sinjale dhe sisteme', 'MANDATORY', None, 6.0, 3, 1, 1, 'vjosa-shatri', 'arben-mashkulli', False, True),
    ('EAR-BSC-S3-C04', 'EAR-BSC-S3', 'Automatika', 'MANDATORY', None, 5.0, 2, 1, 1, 'drilon-bunjaku', 'betim-hoxha', False, True),
    ('EAR-BSC-S3-C05', 'EAR-BSC-S3', 'Bazat e Elektronikës', 'MANDATORY', None, 5.0, 3, 0, 1, 'qamil-kabashi', 'uran-rakovica', False, True),
    ('EAR-BSC-S3-C06', 'EAR-BSC-S3', 'Matjet elektronike', 'MANDATORY', None, 4.0, 2, 0, 1, 'milaim-zabeli', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S4-C01', 'EAR-BSC-S4', 'Interneti i gjërave', 'MANDATORY', None, 6.0, 2, 0, 2, 'drilon-bunjaku', 'faruk-ahmeti', True, True),
    ('EAR-BSC-S4-C02', 'EAR-BSC-S4', 'Elektroenergjetika', 'MANDATORY', None, 5.0, 2, 1, 1, 'vezir-rexhepi', 'faton-mehmeti', True, True),
    ('EAR-BSC-S4-C03', 'EAR-BSC-S4', 'Fushat dhe valët elektromagnetike', 'MANDATORY', None, 5.0, 2, 1, 1, 'vjosa-shatri', 'miranda-kukaj', True, True),
    ('EAR-BSC-S4-C04', 'EAR-BSC-S4', 'Sinjalet diskrete dhe përpunimi digjital', 'MANDATORY', None, 5.0, 2, 0, 2, 'faton-maliqi', 'arben-mashkulli', True, True),
    ('EAR-BSC-S4-C05', 'EAR-BSC-S4', 'Arkitektura e kompjuterëve', 'MANDATORY', None, 5.0, 2, 0, 2, 'qamil-kabashi', 'betim-hoxha', True, True),
    ('EAR-BSC-S4-C06', 'EAR-BSC-S4', 'Menaxhimi i projekteve', 'MANDATORY', None, 4.0, 2, 1, 0, 'nora-sadiku-dushi', 'uran-rakovica', True, True),
    ('EAR-BSC-S5-C01', 'EAR-BSC-S5', 'Komponentët elektronike', 'MANDATORY', None, 6.0, 3, 0, 1, 'milaim-zabeli', 'uran-rakovica', False, True),
    ('EAR-BSC-S5-C02', 'EAR-BSC-S5', 'Elektronika digjitale', 'MANDATORY', None, 6.0, 2, 0, 2, 'sabrije-osmanaj', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S5-C03', 'EAR-BSC-S5', 'Elektronika energjetike', 'MANDATORY', None, 5.0, 2, 0, 2, 'sabrije-osmanaj', 'faton-mehmeti', False, True),
    ('EAR-BSC-S5-C04', 'EAR-BSC-S5', 'Optoelektronika', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'milaim-zabeli', 'miranda-kukaj', False, True),
    ('EAR-BSC-S5-C05', 'EAR-BSC-S5', 'Senzoret dhe Aktuatoret', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'faton-maliqi', 'arben-mashkulli', False, True),
    ('EAR-BSC-S5-C06', 'EAR-BSC-S5', 'Komunikimet elektronike', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'vjosa-shatri', 'betim-hoxha', False, True),
    ('EAR-BSC-S5-C07', 'EAR-BSC-S5', 'Inteligjenca artificiale', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'partneret-industrise', 'uran-rakovica', False, True),
    ('EAR-BSC-S5-C08', 'EAR-BSC-S5', 'Bazat e mekatronikës', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'drilon-bunjaku', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S5-C09', 'EAR-BSC-S5', 'Dirigjuesit e Programueshem Logjik', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'qamil-kabashi', 'faton-mehmeti', False, True),
    ('EAR-BSC-S5-C10', 'EAR-BSC-S5', 'Ndërmarrësi dhe Inovacion', 'ELECTIVE', 'EAR-BSC-S5-E1', 3.0, 2, 0, 0, 'nora-sadiku-dushi', 'miranda-kukaj', False, True),
    ('EAR-BSC-S5-C11', 'EAR-BSC-S5', 'Menaxhmenti në Inxhinieri', 'ELECTIVE', 'EAR-BSC-S5-E1', 3.0, 2, 0, 0, 'nora-sadiku-dushi', 'arben-mashkulli', False, True),
    ('EAR-BSC-S5-C12', 'EAR-BSC-S5', 'Sistemet e rregullimit automatik', 'MANDATORY', None, 6.0, 2, 1, 2, 'drilon-bunjaku', 'betim-hoxha', False, True),
    ('EAR-BSC-S5-C13', 'EAR-BSC-S5', 'Bazat e robotikës', 'MANDATORY', None, 5.0, 2, 0, 2, 'lavdim-kurtaj', 'uran-rakovica', False, True),
    ('EAR-BSC-S5-C14', 'EAR-BSC-S5', 'Aktuatorët e mençur dhe ngasjet', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'lavdim-kurtaj', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S5-C15', 'EAR-BSC-S5', 'Sensorët e mençur', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'drilon-bunjaku', 'faton-mehmeti', False, True),
    ('EAR-BSC-S5-C16', 'EAR-BSC-S5', 'Komunikimet në automatikë', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'lavdim-kurtaj', 'miranda-kukaj', False, True),
    ('EAR-BSC-S5-C17', 'EAR-BSC-S5', 'Metodat e elementeve të fundme', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'vjosa-shatri', 'arben-mashkulli', False, True),
    ('EAR-BSC-S5-C18', 'EAR-BSC-S5', 'Sistemet operative', 'ELECTIVE', 'EAR-BSC-S5-E1', 5.0, 2, 0, 2, 'dhurate-hyseni', 'betim-hoxha', False, True),
    ('EAR-BSC-S6-C01', 'EAR-BSC-S6', 'Mikroelektronika', 'MANDATORY', None, 5.0, 2, 1, 1, 'milaim-zabeli', 'betim-hoxha', False, True),
    ('EAR-BSC-S6-C02', 'EAR-BSC-S6', 'Elektronika analoge', 'MANDATORY', None, 5.0, 2, 0, 2, 'qamil-kabashi', 'uran-rakovica', False, True),
    ('EAR-BSC-S6-C03', 'EAR-BSC-S6', 'Siguria kibernetike', 'MANDATORY', None, 5.0, 2, 0, 2, 'blerim-rexha', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S6-C04', 'EAR-BSC-S6', 'Machine Learning', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'faton-maliqi', 'faton-mehmeti', False, True),
    ('EAR-BSC-S6-C05', 'EAR-BSC-S6', 'Bazat e robotikës', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'lavdim-kurtaj', 'miranda-kukaj', False, True),
    ('EAR-BSC-S6-C06', 'EAR-BSC-S6', 'Teknologjia e komunikimeve optike', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'milaim-zabeli', 'arben-mashkulli', False, True),
    ('EAR-BSC-S6-C07', 'EAR-BSC-S6', 'Sistemet e ndërthurura', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'partneret-industrise', 'betim-hoxha', False, True),
    ('EAR-BSC-S6-C08', 'EAR-BSC-S6', 'Projektimi i qarqeve elektronike me kompjuter', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'milaim-zabeli', 'uran-rakovica', False, True),
    ('EAR-BSC-S6-C09', 'EAR-BSC-S6', 'Praktika profesionale', 'MANDATORY', None, 5.0, 2, 0, 0, 'departamenti-fiek', 'faruk-ahmeti', False, False),
    ('EAR-BSC-S6-C10', 'EAR-BSC-S6', 'Punimi i Diplomës', 'MANDATORY', None, 5.0, 0, 0, 0, 'departamenti-fiek', 'faton-mehmeti', False, False),
    ('EAR-BSC-S6-C11', 'EAR-BSC-S6', 'Modelimi dhe simulimi', 'MANDATORY', None, 5.0, 2, 0, 2, 'drilon-bunjaku', 'miranda-kukaj', False, True),
    ('EAR-BSC-S6-C12', 'EAR-BSC-S6', 'Sistemet digjitale të rregullimit', 'MANDATORY', None, 5.0, 2, 0, 2, 'lavdim-kurtaj', 'arben-mashkulli', False, True),
    ('EAR-BSC-S6-C13', 'EAR-BSC-S6', 'Sistemet jolineare të rregullimit', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'sabrije-osmanaj', 'betim-hoxha', False, True),
    ('EAR-BSC-S6-C14', 'EAR-BSC-S6', 'Sistemet e rregullimit ne kohe reale', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'lavdim-kurtaj', 'uran-rakovica', False, True),
    ('EAR-BSC-S6-C15', 'EAR-BSC-S6', 'Computer Data Acquisition and Analysis', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'drilon-bunjaku', 'faruk-ahmeti', False, True),
    ('EAR-BSC-S6-C16', 'EAR-BSC-S6', 'Automatizimi i objekteve të banimit', 'ELECTIVE', 'EAR-BSC-S6-E1', 5.0, 2, 0, 2, 'lavdim-kurtaj', 'faton-mehmeti', False, True),
    ('EAR-BSC-S6-C17', 'EAR-BSC-S6', 'Tema e diplomës bachelor', 'MANDATORY', None, 5.0, 0, 0, 0, 'departamenti-fiek', 'miranda-kukaj', False, False),
    ('EAR-MSC-S1-C01', 'EAR-MSC-S1', 'Qarqet dhe sinjalet në sisteme', 'MANDATORY', None, 7.0, 3, 1, 1, 'faton-maliqi', 'arben-mashkulli', False, True),
    ('EAR-MSC-S1-C02', 'EAR-MSC-S1', 'Automatizimi i proceseve industriale', 'MANDATORY', None, 6.0, 2, 0, 2, 'drilon-bunjaku', 'betim-hoxha', False, True),
    ('EAR-MSC-S1-C03', 'EAR-MSC-S1', 'Metodologjia e hulumtimit shkencor', 'MANDATORY', None, 5.0, 2, 1, 0, 'milaim-zabeli', 'uran-rakovica', False, True),
    ('EAR-MSC-S1-C04', 'EAR-MSC-S1', 'Rregullimi i ngasjeve elektromotorike', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'qamil-kabashi', 'faruk-ahmeti', False, True),
    ('EAR-MSC-S1-C05', 'EAR-MSC-S1', 'Sensorët dhe aktuatorët në robotikë', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'lavdim-kurtaj', 'faton-mehmeti', False, True),
    ('EAR-MSC-S1-C06', 'EAR-MSC-S1', 'Cyber Physical Systems', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'artan-mazrekaj', 'miranda-kukaj', False, True),
    ('EAR-MSC-S1-C07', 'EAR-MSC-S1', 'Teknologjia VLSI', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'milaim-zabeli', 'arben-mashkulli', False, True),
    ('EAR-MSC-S1-C08', 'EAR-MSC-S1', 'Matjet dhe sensorët në biomedicinë', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'sabrije-osmanaj', 'betim-hoxha', False, True),
    ('EAR-MSC-S1-C09', 'EAR-MSC-S1', 'Elektronika energjetike e avancuar', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'qamil-kabashi', 'uran-rakovica', False, True),
    ('EAR-MSC-S1-C10', 'EAR-MSC-S1', 'Siguria Kibernetike', 'ELECTIVE', 'EAR-MSC-S1-E1', 6.0, 2, 0, 2, 'blerim-rexha', 'faruk-ahmeti', False, True),
    ('EAR-MSC-S2-C01', 'EAR-MSC-S2', 'Projektimi digjital', 'MANDATORY', None, 6.0, 2, 0, 2, 'milaim-zabeli', 'miranda-kukaj', True, True),
    ('EAR-MSC-S2-C02', 'EAR-MSC-S2', 'Sistemet e dedikuara (embedded)', 'MANDATORY', None, 6.0, 2, 0, 2, 'faton-maliqi', 'arben-mashkulli', True, True),
    ('EAR-MSC-S2-C03', 'EAR-MSC-S2', 'Robotika dhe automatizimi', 'MANDATORY', None, 6.0, 2, 0, 2, 'lavdim-kurtaj', 'betim-hoxha', True, True),
    ('EAR-MSC-S2-C04', 'EAR-MSC-S2', 'Identifikimi i sistemeve', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'faton-maliqi', 'uran-rakovica', True, True),
    ('EAR-MSC-S2-C05', 'EAR-MSC-S2', 'Rregullimi i proceseve me kompjuter', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'drilon-bunjaku', 'faruk-ahmeti', True, True),
    ('EAR-MSC-S2-C06', 'EAR-MSC-S2', 'Sistemet operative në kohë reale', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'lavdim-kurtaj', 'faton-mehmeti', False, True),
    ('EAR-MSC-S2-C07', 'EAR-MSC-S2', 'Analiza e sistemeve me elemente të fundme', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'vjosa-shatri', 'miranda-kukaj', False, True),
    ('EAR-MSC-S2-C08', 'EAR-MSC-S2', 'Teknologjitë e imazhimit biomedicional', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'sabrije-osmanaj', 'arben-mashkulli', False, True),
    ('EAR-MSC-S2-C09', 'EAR-MSC-S2', 'Qarqet mikroelektronike digjitale', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'milaim-zabeli', 'betim-hoxha', False, True),
    ('EAR-MSC-S2-C10', 'EAR-MSC-S2', 'Tema te avancuara ne Machine Learning', 'ELECTIVE', 'EAR-MSC-S2-E1', 6.0, 2, 0, 2, 'faton-maliqi', 'uran-rakovica', False, True),
    ('EAR-MSC-S3-C01', 'EAR-MSC-S3', 'Burimet alternative të energjisë elektrike', 'MANDATORY', None, 6.0, 2, 0, 2, 'qamil-kabashi', 'faton-mehmeti', False, True),
    ('EAR-MSC-S3-C02', 'EAR-MSC-S3', 'Të pamurit e makinës', 'MANDATORY', None, 6.0, 2, 0, 2, 'lavdim-kurtaj', 'miranda-kukaj', False, True),
    ('EAR-MSC-S3-C03', 'EAR-MSC-S3', 'Cloud Computing', 'MANDATORY', None, 6.0, 2, 0, 2, 'artan-mazrekaj', 'arben-mashkulli', False, True),
    ('EAR-MSC-S3-C04', 'EAR-MSC-S3', 'Inteligjenca artificiale', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'faton-maliqi', 'betim-hoxha', False, True),
    ('EAR-MSC-S3-C05', 'EAR-MSC-S3', 'Robotët mobil', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'lavdim-kurtaj', 'uran-rakovica', False, True),
    ('EAR-MSC-S3-C06', 'EAR-MSC-S3', 'Rrjetat neurale dhe logjika fazi', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'lavdim-kurtaj', 'faruk-ahmeti', False, True),
    ('EAR-MSC-S3-C07', 'EAR-MSC-S3', 'Microelectronic Systems', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'milaim-zabeli', 'faton-mehmeti', False, True),
    ('EAR-MSC-S3-C08', 'EAR-MSC-S3', 'Akustika e të folurit dhe muzikës', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'vjosa-shatri', 'miranda-kukaj', False, True),
    ('EAR-MSC-S3-C09', 'EAR-MSC-S3', 'Instrumentacioni biomedicinale', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'sabrije-osmanaj', 'arben-mashkulli', False, True),
    ('EAR-MSC-S3-C10', 'EAR-MSC-S3', 'Energjia dhe mjedisi', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 0, 2, 'sabrije-osmanaj', 'betim-hoxha', False, True),
    ('EAR-MSC-S3-C11', 'EAR-MSC-S3', 'Menaxhmenti strategjik', 'ELECTIVE', 'EAR-MSC-S3-E1', 6.0, 2, 2, 0, 'nora-sadiku-dushi', 'uran-rakovica', False, True),
    ('EAR-MSC-S4-C01', 'EAR-MSC-S4', 'Punimi i diplomës master', 'MANDATORY', None, 30.0, 0, 0, 0, 'departamenti-fiek', 'faruk-ahmeti', False, False),
    ('EE-BSC-S1-C01', 'EE-BSC-S1', 'Fizika për inxhinieri 1', 'MANDATORY', None, 6.0, 2, 1, 1, 'valon-veliu', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S1-C02', 'EE-BSC-S1', 'Bazat e inxhinierisë elektrike 1', 'MANDATORY', None, 6.0, 3, 1, 1, 'vjosa-shatri', 'arben-mashkulli', False, True),
    ('EE-BSC-S1-C03', 'EE-BSC-S1', 'Bazat e programimit', 'MANDATORY', None, 6.0, 2, 0, 2, 'avni-rexhepi', 'petrit-emini', False, True),
    ('EE-BSC-S1-C04', 'EE-BSC-S1', 'Shkathtësitë e komunikimit', 'MANDATORY', None, 3.0, 2, 0, 0, 'blerim-rexha', 'enis-riza', False, True),
    ('EE-BSC-S1-C05', 'EE-BSC-S1', 'Praktikumi në matematikë', 'ELECTIVE', 'EE-BSC-S1-E1', 2.0, 2, 0, 0, 'departamenti-fiek', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S1-C06', 'EE-BSC-S1', 'Veglat bazë softuerike', 'ELECTIVE', 'EE-BSC-S1-E1', 2.0, 2, 0, 0, 'besmir-sejdiu', 'arben-mashkulli', False, True),
    ('EE-BSC-S1-C07', 'EE-BSC-S1', 'Algjebra lineare dhe kalkulus 1', 'MANDATORY', None, 7.0, 3, 3, 0, 'shqipe-lohaj', 'petrit-emini', False, True),
    ('EE-BSC-S2-C01', 'EE-BSC-S2', 'Fizika për inxhinieri 2', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'arben-mashkulli', False, True),
    ('EE-BSC-S2-C02', 'EE-BSC-S2', 'Bazat e inxhinierisë elektrike 2', 'MANDATORY', None, 6.0, 3, 1, 1, 'vjosa-shatri', 'petrit-emini', False, True),
    ('EE-BSC-S2-C03', 'EE-BSC-S2', 'Algoritmet dhe struktura e të dhënave', 'MANDATORY', None, 6.0, 2, 0, 2, 'mimoza-ibrani', 'enis-riza', False, True),
    ('EE-BSC-S2-C04', 'EE-BSC-S2', 'Qarqet digjitale', 'MANDATORY', None, 6.0, 2, 1, 1, 'sabrije-osmanaj', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S2-C05', 'EE-BSC-S2', 'Gjeometri analitike dhe Kalkulus 2', 'MANDATORY', None, 7.0, 3, 3, 0, 'shqipe-lohaj', 'arben-mashkulli', False, True),
    ('EE-BSC-S3-C01', 'EE-BSC-S3', 'Materialet elektrike', 'MANDATORY', None, 4.0, 2, 0, 2, 'departamenti-fiek', 'petrit-emini', False, True),
    ('EE-BSC-S3-C02', 'EE-BSC-S3', 'Matjet Elektrike', 'MANDATORY', None, 5.0, 3, 0, 2, 'arben-gjukaj', 'enis-riza', False, True),
    ('EE-BSC-S3-C03', 'EE-BSC-S3', 'Bazat e Elektroenergjetikës', 'MANDATORY', None, 6.0, 3, 2, 0, 'nuri-berisha', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S3-C04', 'EE-BSC-S3', 'Electronika', 'MANDATORY', None, 5.0, 3, 0, 1, 'qamil-kabashi', 'arben-mashkulli', False, True),
    ('EE-BSC-S3-C05', 'EE-BSC-S3', 'Bazat e automatikës', 'ELECTIVE', 'EE-BSC-S3-E1', 4.0, 2, 1, 1, 'lavdim-kurtaj', 'petrit-emini', False, True),
    ('EE-BSC-S3-C06', 'EE-BSC-S3', 'Sinjalet dhe sistemet', 'ELECTIVE', 'EE-BSC-S3-E1', 4.0, 2, 1, 1, 'vjosa-shatri', 'enis-riza', False, True),
    ('EE-BSC-S3-C07', 'EE-BSC-S3', 'Programimi i orientuar në objekte', 'ELECTIVE', 'EE-BSC-S3-E1', 4.0, 2, 0, 2, 'isak-shabani', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S3-C08', 'EE-BSC-S3', 'Aplikacionet softuerike në elektroenergjetikë', 'ELECTIVE', 'EE-BSC-S3-E1', 4.0, 2, 0, 2, 'vezir-rexhepi', 'arben-mashkulli', False, True),
    ('EE-BSC-S3-C09', 'EE-BSC-S3', 'Kalkulus 3 dhe probabilitet (EE)', 'MANDATORY', None, 6.0, 3, 2, 0, 'shqipe-lohaj', 'petrit-emini', False, True),
    ('EE-BSC-S4-C01', 'EE-BSC-S4', 'Energjia dhe mjedisi', 'MANDATORY', None, 5.0, 2, 1, 1, 'arben-gjukaj', 'enis-riza', True, True),
    ('EE-BSC-S4-C02', 'EE-BSC-S4', 'Centralet elektrike', 'MANDATORY', None, 6.0, 3, 2, 0, 'arben-gjukaj', 'nafije-shabani-dallku', True, True),
    ('EE-BSC-S4-C03', 'EE-BSC-S4', 'Fushat dhe valët elektromagnetike', 'MANDATORY', None, 5.0, 3, 0, 1, 'mimoza-ibrani', 'arben-mashkulli', True, True),
    ('EE-BSC-S4-C04', 'EE-BSC-S4', 'Menaxhimi i energjisë dhe auditimi i efiçiencës së energjisë', 'MANDATORY', None, 4.0, 2, 1, 0, 'vezir-rexhepi', 'petrit-emini', True, True),
    ('EE-BSC-S4-C05', 'EE-BSC-S4', 'Instrumentacioni matës në elektroenergjetikë', 'ELECTIVE', 'EE-BSC-S4-E1', 4.0, 2, 2, 0, 'departamenti-fiek', 'enis-riza', True, True),
    ('EE-BSC-S4-C06', 'EE-BSC-S4', 'Teknika e sigurimit në impiantet elektrike', 'ELECTIVE', 'EE-BSC-S4-E1', 4.0, 2, 0, 2, 'arben-gjukaj', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S4-C07', 'EE-BSC-S4', 'Kualiteti i Fuqisë', 'ELECTIVE', 'EE-BSC-S4-E1', 4.0, 2, 0, 1, 'nuri-berisha', 'arben-mashkulli', False, True),
    ('EE-BSC-S4-C08', 'EE-BSC-S4', 'Makinat elektrike dhe transformatorët', 'MANDATORY', None, 6.0, 3, 2, 1, 'vezir-rexhepi', 'petrit-emini', True, True),
    ('EE-BSC-S5-C01', 'EE-BSC-S5', 'Ekonomia e tregjeve elektrike', 'MANDATORY', None, 5.0, 2, 2, 0, 'vezir-rexhepi', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S5-C02', 'EE-BSC-S5', 'Bartja dhe shpërndarja e energjisë elektrike', 'MANDATORY', None, 5.0, 2, 2, 1, 'nuri-berisha', 'arben-mashkulli', False, True),
    ('EE-BSC-S5-C03', 'EE-BSC-S5', 'Stabilimentet elektroenergjetike', 'MANDATORY', None, 5.0, 2, 1, 1, 'departamenti-fiek', 'petrit-emini', False, True),
    ('EE-BSC-S5-C04', 'EE-BSC-S5', 'Instalimet elektrike dhe rrjetat e tensionit të ultë', 'MANDATORY', None, 6.0, 3, 2, 1, 'arben-gjukaj', 'enis-riza', False, True),
    ('EE-BSC-S5-C05', 'EE-BSC-S5', 'Burimet e ripërtëritshme të energjisë', 'MANDATORY', None, 5.0, 2, 0, 1, 'vezir-rexhepi', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S5-C06', 'EE-BSC-S5', 'Standardet teknike dhe rregullative', 'ELECTIVE', 'EE-BSC-S5-E1', 4.0, 2, 0, 1, 'partneret-industrise', 'arben-mashkulli', False, True),
    ('EE-BSC-S5-C07', 'EE-BSC-S5', 'Elektronika energjetike', 'ELECTIVE', 'EE-BSC-S5-E1', 4.0, 2, 1, 1, 'sabrije-osmanaj', 'petrit-emini', False, True),
    ('EE-BSC-S5-C08', 'EE-BSC-S5', 'Rrjetat elektrike', 'ELECTIVE', 'EE-BSC-S5-E1', 4.0, 2, 0, 1, 'nuri-berisha', 'enis-riza', False, True),
    ('EE-BSC-S5-C09', 'EE-BSC-S5', 'Të dhënat e komunikimeve', 'ELECTIVE', 'EE-BSC-S5-E1', 4.0, 2, 0, 1, 'bujar-krasniqi', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S6-C01', 'EE-BSC-S6', 'Ngasjet elektrike', 'MANDATORY', None, 6.0, 3, 2, 1, 'nuri-berisha', 'arben-mashkulli', False, True),
    ('EE-BSC-S6-C02', 'EE-BSC-S6', 'Mbrojtje rele', 'MANDATORY', None, 5.0, 2, 1, 1, 'vezir-rexhepi', 'petrit-emini', False, True),
    ('EE-BSC-S6-C03', 'EE-BSC-S6', 'Bazat e rrjetave të mençura', 'MANDATORY', None, 5.0, 2, 1, 1, 'nuri-berisha', 'enis-riza', False, True),
    ('EE-BSC-S6-C04', 'EE-BSC-S6', 'Praktika profesionale', 'MANDATORY', None, 7.0, 0, 0, 0, 'arben-gjukaj', 'nafije-shabani-dallku', False, False),
    ('EE-BSC-S6-C05', 'EE-BSC-S6', 'Energjia solare dhe sistemet fotovoltaike', 'ELECTIVE', 'EE-BSC-S6-E5', 4.0, 2, 0, 1, 'vezir-rexhepi', 'arben-mashkulli', False, True),
    ('EE-BSC-S6-C06', 'EE-BSC-S6', 'Energjia e erës', 'ELECTIVE', 'EE-BSC-S6-E5', 4.0, 2, 0, 1, 'departamenti-fiek', 'petrit-emini', False, True),
    ('EE-BSC-S6-C07', 'EE-BSC-S6', 'Sistemet për ruajtjen e energjisë', 'ELECTIVE', 'EE-BSC-S6-E5', 4.0, 2, 0, 1, 'partneret-industrise', 'enis-riza', False, True),
    ('EE-BSC-S6-C08', 'EE-BSC-S6', 'Marketingu për Inxhinierë', 'ELECTIVE', 'EE-BSC-S6-E6', 3.0, 2, 1, 0, 'nora-sadiku-dushi', 'nafije-shabani-dallku', False, True),
    ('EE-BSC-S6-C09', 'EE-BSC-S6', 'Ndërmarrësia dhe Inovacioni', 'ELECTIVE', 'EE-BSC-S6-E6', 3.0, 2, 1, 0, 'nora-sadiku-dushi', 'arben-mashkulli', False, True),
    ('EE-BSC-S6-C10', 'EE-BSC-S6', 'Menaxhmenti në Inxhinieri', 'ELECTIVE', 'EE-BSC-S6-E6', 3.0, 2, 1, 0, 'nora-sadiku-dushi', 'petrit-emini', False, True),
    ('EE-MSC-S1-C01', 'EE-MSC-S1', 'Analiza e Sistemeve Elektroenergjetike', 'MANDATORY', None, 6.0, 2, 1, 2, 'nuri-berisha', 'nafije-shabani-dallku', False, True),
    ('EE-MSC-S1-C02', 'EE-MSC-S1', 'Prodhimi i Energjisë Konvencionale dhe të Ripërtëritshme', 'MANDATORY', None, 6.0, 2, 1, 2, 'arben-gjukaj', 'arben-mashkulli', False, True),
    ('EE-MSC-S1-C03', 'EE-MSC-S1', 'Teknikat e Tensioneve të Larta', 'MANDATORY', None, 6.0, 2, 1, 2, 'arben-gjukaj', 'petrit-emini', False, True),
    ('EE-MSC-S1-C04', 'EE-MSC-S1', 'Sistemet Elektroenergjetike të Shpërndarjes dhe Industriale', 'MANDATORY', None, 6.0, 2, 1, 2, 'nuri-berisha', 'enis-riza', False, True),
    ('EE-MSC-S1-C05', 'EE-MSC-S1', 'Menaxhimi i Projekteve', 'MANDATORY', None, 6.0, 2, 2, 0, 'nora-sadiku-dushi', 'nafije-shabani-dallku', False, True),
    ('EE-MSC-S2-C01', 'EE-MSC-S2', 'Integrimi i Burimeve të Ripërtëritshme të Energjisë në Sistemet Elektroenergjetike', 'MANDATORY', None, 6.0, 2, 1, 2, 'vezir-rexhepi', 'arben-mashkulli', True, True),
    ('EE-MSC-S2-C02', 'EE-MSC-S2', 'Sistemet për Ruajtjen e Energjisë dhe Teknologjitë e Avancuara', 'MANDATORY', None, 6.0, 2, 1, 2, 'qamil-kabashi', 'petrit-emini', True, True),
    ('EE-MSC-S2-C03', 'EE-MSC-S2', 'Metodologjia Shkencore dhe Kërkimore', 'MANDATORY', None, 6.0, 2, 2, 0, 'milaim-zabeli', 'enis-riza', True, True),
    ('EE-MSC-S2-C04', 'EE-MSC-S2', 'Aplikimi i Softuereve në Projektim të Sistemeve Elektroenergjetike', 'ELECTIVE', 'EE-MSC-S2-E4', 6.0, 2, 0, 2, 'departamenti-fiek', 'nafije-shabani-dallku', True, True),
    ('EE-MSC-S2-C05', 'EE-MSC-S2', 'Elektronika e Avancuar e Fuqisë', 'ELECTIVE', 'EE-MSC-S2-E4', 6.0, 2, 1, 2, 'qamil-kabashi', 'arben-mashkulli', False, True),
    ('EE-MSC-S2-C06', 'EE-MSC-S2', 'Metodat Matematikore në Inxhinieri', 'ELECTIVE', 'EE-MSC-S2-E4', 6.0, 2, 2, 0, 'valdete-rexhebeqaj-hamiti', 'petrit-emini', False, True),
    ('EE-MSC-S2-C07', 'EE-MSC-S2', 'Menaxhimi Ekonomik i Sistemeve Elektroenergjetike', 'ELECTIVE', 'EE-MSC-S2-E4', 6.0, 2, 2, 0, 'departamenti-fiek', 'enis-riza', False, True),
    ('EE-MSC-S2-C08', 'EE-MSC-S2', 'Politikat Ekonomike dhe Ambientale të EU-së', 'ELECTIVE', 'EE-MSC-S2-E4', 6.0, 2, 2, 0, 'departamenti-fiek', 'nafije-shabani-dallku', False, True),
    ('EE-MSC-S2-C09', 'EE-MSC-S2', 'Menaxhmenti Financiar', 'ELECTIVE', 'EE-MSC-S2-E5', 6.0, 2, 2, 0, 'nora-sadiku-dushi', 'arben-mashkulli', True, True),
    ('EE-MSC-S2-C10', 'EE-MSC-S2', 'Menaxhimi i Burimeve Njerëzore', 'ELECTIVE', 'EE-MSC-S2-E5', 6.0, 2, 2, 0, 'nora-sadiku-dushi', 'petrit-emini', False, True),
    ('EE-MSC-S3-C01', 'EE-MSC-S3', 'Kontrolla dhe Operimi i Sistemeve Elektroenergjetike', 'MANDATORY', None, 6.0, 2, 1, 2, 'vezir-rexhepi', 'petrit-emini', False, True),
    ('EE-MSC-S3-C02', 'EE-MSC-S3', 'Planifikimi i Sistemeve Elektroenergjetike Moderne', 'MANDATORY', None, 6.0, 2, 2, 1, 'arben-gjukaj', 'enis-riza', False, True),
    ('EE-MSC-S3-C03', 'EE-MSC-S3', 'Praktika Profesionale', 'MANDATORY', None, 6.0, 4, 0, 0, 'nuri-berisha', 'nafije-shabani-dallku', False, False),
    ('EE-MSC-S3-C04', 'EE-MSC-S3', 'Sistemet Moderne të Mbrojtjeve Rele', 'ELECTIVE', 'EE-MSC-S3-E4', 6.0, 2, 1, 2, 'departamenti-fiek', 'arben-mashkulli', False, True),
    ('EE-MSC-S3-C05', 'EE-MSC-S3', 'Efiçienca e Energjisë dhe Menaxhimi i Kërkesës', 'ELECTIVE', 'EE-MSC-S3-E4', 6.0, 2, 2, 0, 'vezir-rexhepi', 'petrit-emini', False, True),
    ('EE-MSC-S3-C06', 'EE-MSC-S3', 'Zhvillimi i Rrjeteve të Mençura', 'ELECTIVE', 'EE-MSC-S3-E4', 6.0, 2, 1, 2, 'nuri-berisha', 'enis-riza', False, True),
    ('EE-MSC-S3-C07', 'EE-MSC-S3', 'Analiza e të Dhënave për Energji', 'ELECTIVE', 'EE-MSC-S3-E4', 6.0, 2, 0, 2, 'isak-shabani', 'nafije-shabani-dallku', False, True),
    ('EE-MSC-S3-C08', 'EE-MSC-S3', 'Aplikimi i Inteligjencës Artificiale në Energji', 'ELECTIVE', 'EE-MSC-S3-E4', 6.0, 2, 0, 2, 'lavdim-kurtaj', 'arben-mashkulli', False, True),
    ('EE-MSC-S3-C09', 'EE-MSC-S3', 'Ekonomia Qarkore', 'ELECTIVE', 'EE-MSC-S3-E5', 6.0, 2, 2, 0, 'nora-sadiku-dushi', 'petrit-emini', False, True),
    ('EE-MSC-S3-C10', 'EE-MSC-S3', 'Menaxhmenti Strategjik', 'ELECTIVE', 'EE-MSC-S3-E5', 6.0, 2, 2, 0, 'nora-sadiku-dushi', 'enis-riza', False, True),
    ('EE-MSC-S4-C01', 'EE-MSC-S4', 'Tema e diplomës', 'MANDATORY', None, 30.0, 0, 0, 0, 'departamenti-fiek', 'enis-riza', False, False),
    ('IKS-BSC-S1-C01', 'IKS-BSC-S1', 'Algjebra lineare me Kalkulus 1', 'MANDATORY', None, 7.0, 3, 3, 0, 'qefsere-doko', 'blend-arifaj', False, True),
    ('IKS-BSC-S1-C02', 'IKS-BSC-S1', 'Fizika inxhinierike 1', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'labeat-arbneshi', False, True),
    ('IKS-BSC-S1-C03', 'IKS-BSC-S1', 'Bazat e inxhinierisë elektrike 1', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'adrian-ymeri', False, True),
    ('IKS-BSC-S1-C04', 'IKS-BSC-S1', 'Bazat e programimit', 'MANDATORY', None, 5.0, 2, 0, 2, 'avni-rexhepi', 'jeta-dobruna', False, True),
    ('IKS-BSC-S1-C05', 'IKS-BSC-S1', 'Shkathtësitë e komunikimit', 'MANDATORY', None, 3.0, 2, 0, 0, 'blerim-rexha', 'yllka-kabashi', False, True),
    ('IKS-BSC-S1-C06', 'IKS-BSC-S1', 'Praktikumi në matematikë', 'ELECTIVE', 'IKS-BSC-S1-E1', 3.0, 2, 0, 0, 'departamenti-fiek', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S1-C07', 'IKS-BSC-S1', 'Veglat bazë softuerike', 'ELECTIVE', 'IKS-BSC-S1-E1', 3.0, 2, 0, 0, 'departamenti-fiek', 'blend-arifaj', False, True),
    ('IKS-BSC-S2-C01', 'IKS-BSC-S2', 'Gjeometri analitike me Kalkulus 2', 'MANDATORY', None, 7.0, 3, 3, 0, 'qefsere-doko', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S2-C02', 'IKS-BSC-S2', 'Fizika inxhinierike 2', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'blend-arifaj', False, True),
    ('IKS-BSC-S2-C03', 'IKS-BSC-S2', 'Bazat e inxhinierisë elektrike 2', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'labeat-arbneshi', False, True),
    ('IKS-BSC-S2-C04', 'IKS-BSC-S2', 'Algoritmet dhe strukturat e të dhënave', 'MANDATORY', None, 6.0, 2, 0, 2, 'kadri-sylejmani', 'adrian-ymeri', False, True),
    ('IKS-BSC-S2-C05', 'IKS-BSC-S2', 'Qarqet digjitale', 'MANDATORY', None, 6.0, 2, 1, 1, 'sabrije-osmanaj', 'jeta-dobruna', False, True),
    ('IKS-BSC-S3-C01', 'IKS-BSC-S3', 'Matematika Diskrete me Probabilitet dhe Statistikë', 'MANDATORY', None, 5.0, 2, 2, 0, 'qefsere-doko', 'yllka-kabashi', False, True),
    ('IKS-BSC-S3-C02', 'IKS-BSC-S3', 'Elektronikë', 'MANDATORY', None, 5.0, 2, 1, 1, 'qamil-kabashi', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S3-C03', 'IKS-BSC-S3', 'Legal, Ethical and Social Issues in ICT', 'MANDATORY', None, 5.0, 2, 0, 2, 'dhurate-hyseni', 'blend-arifaj', False, True),
    ('IKS-BSC-S3-C04', 'IKS-BSC-S3', 'Bazat e të dhënave', 'MANDATORY', None, 5.0, 2, 0, 2, 'lule-ahmedi', 'labeat-arbneshi', False, True),
    ('IKS-BSC-S3-C05', 'IKS-BSC-S3', 'Programimi i orientuar në objekte', 'MANDATORY', None, 5.0, 2, 0, 2, 'isak-shabani', 'adrian-ymeri', False, True),
    ('IKS-BSC-S3-C06', 'IKS-BSC-S3', 'Programimi në Ueb nga ana e Klientit', 'MANDATORY', None, 5.0, 2, 0, 2, 'dhurate-hyseni', 'jeta-dobruna', False, True),
    ('IKS-BSC-S4-C01', 'IKS-BSC-S4', 'Arkitektura e kompjuterëve', 'MANDATORY', None, 6.0, 2, 0, 2, 'qamil-kabashi', 'jeta-dobruna', True, True),
    ('IKS-BSC-S4-C02', 'IKS-BSC-S4', 'Rrjetat kompjuterike', 'MANDATORY', None, 5.0, 2, 0, 2, 'blerim-rexha', 'yllka-kabashi', True, True),
    ('IKS-BSC-S4-C03', 'IKS-BSC-S4', 'Siguria e të dhënave', 'MANDATORY', None, 5.0, 2, 0, 2, 'blerim-rexha', 'mihrije-kadriu', True, True),
    ('IKS-BSC-S4-C04', 'IKS-BSC-S4', 'Komunikimi Njeri-Kompjuter', 'MANDATORY', None, 5.0, 2, 0, 2, 'isak-shabani', 'blend-arifaj', True, True),
    ('IKS-BSC-S4-C05', 'IKS-BSC-S4', 'Programimi në Ueb nga ana e Serverit', 'MANDATORY', None, 5.0, 2, 0, 2, 'dhurate-hyseni', 'labeat-arbneshi', True, True),
    ('IKS-BSC-S4-C06', 'IKS-BSC-S4', 'Menaxhimi i projekteve', 'ELECTIVE', 'IKS-BSC-S4-E1', 4.0, 2, 0, 1, 'nora-sadiku-dushi', 'adrian-ymeri', True, True),
    ('IKS-BSC-S4-C07', 'IKS-BSC-S4', 'Marketingu për inxhinierë', 'ELECTIVE', 'IKS-BSC-S4-E1', 4.0, 2, 0, 1, 'nora-sadiku-dushi', 'jeta-dobruna', False, True),
    ('IKS-BSC-S5-C01', 'IKS-BSC-S5', 'Sistemet operative', 'MANDATORY', None, 6.0, 2, 0, 2, 'artan-mazrekaj', 'adrian-ymeri', False, True),
    ('IKS-BSC-S5-C02', 'IKS-BSC-S5', 'Inxhinieria Softuerike', 'MANDATORY', None, 5.0, 2, 0, 2, 'blerim-rexha', 'jeta-dobruna', False, True),
    ('IKS-BSC-S5-C03', 'IKS-BSC-S5', 'Dizajni dhe Analiza e Algoritmeve', 'MANDATORY', None, 5.0, 2, 0, 2, 'avni-rexhepi', 'yllka-kabashi', False, True),
    ('IKS-BSC-S5-C04', 'IKS-BSC-S5', 'Ndërmarrësia dhe Inovacioni', 'MANDATORY', None, 4.0, 2, 0, 1, 'nora-sadiku-dushi', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S5-C05', 'IKS-BSC-S5', 'Mikroprocesorët dhe mikrokontrollerët', 'ELECTIVE', 'IKS-BSC-S5-E5', 5.0, 2, 0, 2, 'lavdim-kurtaj', 'blend-arifaj', False, True),
    ('IKS-BSC-S5-C06', 'IKS-BSC-S5', 'Procesimi i sinjaleve', 'ELECTIVE', 'IKS-BSC-S5-E5', 5.0, 2, 0, 2, 'faton-maliqi', 'labeat-arbneshi', False, True),
    ('IKS-BSC-S5-C07', 'IKS-BSC-S5', 'Siguria në Internet', 'ELECTIVE', 'IKS-BSC-S5-E6', 5.0, 2, 0, 2, 'blerim-rexha', 'adrian-ymeri', False, True),
    ('IKS-BSC-S5-C08', 'IKS-BSC-S5', 'Sigurimi i cilësisë së softuerit', 'ELECTIVE', 'IKS-BSC-S5-E6', 5.0, 2, 0, 2, 'kadri-sylejmani', 'jeta-dobruna', False, True),
    ('IKS-BSC-S5-C09', 'IKS-BSC-S5', 'Gërmimi i të dhënave', 'ELECTIVE', 'IKS-BSC-S5-E6', 5.0, 2, 0, 2, 'lule-ahmedi', 'yllka-kabashi', False, True),
    ('IKS-BSC-S5-C10', 'IKS-BSC-S5', 'Gjuhët e Skriptimit', 'ELECTIVE', 'IKS-BSC-S5-E6', 5.0, 2, 0, 2, 'kadri-sylejmani', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S5-C11', 'IKS-BSC-S5', 'Analiza e të dhënave', 'ELECTIVE', 'IKS-BSC-S5-E6', 5.0, 2, 0, 2, 'blerim-rexha', 'blend-arifaj', False, True),
    ('IKS-BSC-S6-C01', 'IKS-BSC-S6', 'Praktika profesionale', 'MANDATORY', None, 6.0, 0, 0, 0, 'departamenti-fiek', 'labeat-arbneshi', False, False),
    ('IKS-BSC-S6-C02', 'IKS-BSC-S6', 'Projekti profesional', 'MANDATORY', None, 6.0, 2, 0, 2, 'departamenti-fiek', 'adrian-ymeri', False, True),
    ('IKS-BSC-S6-C03', 'IKS-BSC-S6', 'Sistemet e shpërndara', 'MANDATORY', None, 6.0, 2, 0, 2, 'isak-shabani', 'jeta-dobruna', False, True),
    ('IKS-BSC-S6-C04', 'IKS-BSC-S6', 'Cloud Computing', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'artan-mazrekaj', 'yllka-kabashi', False, True),
    ('IKS-BSC-S6-C05', 'IKS-BSC-S6', 'Bazat e Inteligjencës Artificiale', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'avni-rexhepi', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S6-C06', 'IKS-BSC-S6', 'Programimi i lojërave', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'blerim-rexha', 'blend-arifaj', False, True),
    ('IKS-BSC-S6-C07', 'IKS-BSC-S6', 'Augmented, Virtual and Mixed Reality', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'lule-ahmedi', 'labeat-arbneshi', False, True),
    ('IKS-BSC-S6-C08', 'IKS-BSC-S6', 'Data Engineering', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'lule-ahmedi', 'adrian-ymeri', False, True),
    ('IKS-BSC-S6-C09', 'IKS-BSC-S6', 'Zhvillimi i bazuar në Platformë', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'lule-ahmedi', 'jeta-dobruna', False, True),
    ('IKS-BSC-S6-C10', 'IKS-BSC-S6', 'Bazat e teknologjive me Blockchain', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'blerim-rexha', 'yllka-kabashi', False, True),
    ('IKS-BSC-S6-C11', 'IKS-BSC-S6', 'Komunikimi i të dhënave', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'bujar-krasniqi', 'mihrije-kadriu', False, True),
    ('IKS-BSC-S6-C12', 'IKS-BSC-S6', 'Hyrje në modelet e mëdha gjuhësore', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'blerim-rexha', 'blend-arifaj', False, True),
    ('IKS-BSC-S6-C13', 'IKS-BSC-S6', 'Biometrika & Forenzika', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'blerim-rexha', 'labeat-arbneshi', False, True),
    ('IKS-BSC-S6-C14', 'IKS-BSC-S6', 'Bootcamp për Kodim dhe Algoritme', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'kadri-sylejmani', 'adrian-ymeri', False, True),
    ('IKS-BSC-S6-C15', 'IKS-BSC-S6', 'Embedded Systems', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 2, 'faton-maliqi', 'jeta-dobruna', False, True),
    ('IKS-BSC-S6-C16', 'IKS-BSC-S6', 'Tema e diplomës bachelor', 'ELECTIVE', 'IKS-BSC-S6-E1', 6.0, 2, 0, 0, 'departamenti-fiek', 'yllka-kabashi', False, False),
    ('IKS-MSC-S1-C01', 'IKS-MSC-S1', 'Algoritmet e Avancuara', 'MANDATORY', None, 6.0, 2, 0, 2, 'kadri-sylejmani', 'blend-arifaj', False, True),
    ('IKS-MSC-S1-C02', 'IKS-MSC-S1', 'Përgatitja dhe vizualizimi i të dhënave', 'MANDATORY', None, 6.0, 2, 0, 2, 'lule-ahmedi', 'labeat-arbneshi', False, True),
    ('IKS-MSC-S1-C03', 'IKS-MSC-S1', 'Inteligjenca Artificiale', 'MANDATORY', None, 6.0, 2, 0, 2, 'avni-rexhepi', 'adrian-ymeri', False, True),
    ('IKS-MSC-S1-C04', 'IKS-MSC-S1', 'Siguria e informacionit', 'MANDATORY', None, 6.0, 2, 0, 2, 'blerim-rexha', 'jeta-dobruna', False, True),
    ('IKS-MSC-S1-C05', 'IKS-MSC-S1', 'Dizajni dhe analiza e softuerit', 'MANDATORY', None, 6.0, 2, 0, 2, 'isak-shabani', 'yllka-kabashi', False, True),
    ('IKS-MSC-S2-C01', 'IKS-MSC-S2', 'Gjuha e makinës', 'MANDATORY', None, 6.0, 2, 0, 2, 'lule-ahmedi', 'mihrije-kadriu', True, True),
    ('IKS-MSC-S2-C02', 'IKS-MSC-S2', 'Sistemet e Orientuara në Shërbime', 'MANDATORY', None, 6.0, 2, 0, 2, 'isak-shabani', 'blend-arifaj', True, True),
    ('IKS-MSC-S2-C03', 'IKS-MSC-S2', 'Metodologjitë hulumtuese', 'MANDATORY', None, 6.0, 2, 0, 2, 'dhurate-hyseni', 'labeat-arbneshi', True, True),
    ('IKS-MSC-S2-C04', 'IKS-MSC-S2', 'Uebi semantik', 'ELECTIVE', 'IKS-MSC-S2-E1', 6.0, 2, 0, 2, 'lule-ahmedi', 'adrian-ymeri', True, True),
    ('IKS-MSC-S2-C05', 'IKS-MSC-S2', 'Algoritmet e inspiruara nga natyra', 'ELECTIVE', 'IKS-MSC-S2-E1', 6.0, 2, 0, 2, 'kadri-sylejmani', 'jeta-dobruna', True, True),
    ('IKS-MSC-S2-C06', 'IKS-MSC-S2', 'Interneti i gjërave', 'ELECTIVE', 'IKS-MSC-S2-E1', 6.0, 2, 0, 2, 'besmir-sejdiu', 'yllka-kabashi', False, True),
    ('IKS-MSC-S3-C01', 'IKS-MSC-S3', 'e-Qeverisja', 'MANDATORY', None, 6.0, 2, 0, 2, 'isak-shabani', 'yllka-kabashi', False, True),
    ('IKS-MSC-S3-C02', 'IKS-MSC-S3', 'Menaxhimi i Burimeve në Cloud Computing', 'MANDATORY', None, 6.0, 2, 0, 2, 'artan-mazrekaj', 'mihrije-kadriu', False, True),
    ('IKS-MSC-S3-C03', 'IKS-MSC-S3', 'Praktika profesionale për projekte inovative', 'MANDATORY', None, 6.0, 2, 0, 2, 'besmir-sejdiu', 'blend-arifaj', False, False),
    ('IKS-MSC-S3-C04', 'IKS-MSC-S3', 'Procesimi i Gjuhëve Natyrale', 'ELECTIVE', 'IKS-MSC-S3-E1', 6.0, 2, 0, 2, 'lule-ahmedi', 'labeat-arbneshi', False, True),
    ('IKS-MSC-S3-C05', 'IKS-MSC-S3', 'Teknologjitë Blockchain', 'ELECTIVE', 'IKS-MSC-S3-E1', 6.0, 2, 0, 2, 'blerim-rexha', 'adrian-ymeri', False, True),
    ('IKS-MSC-S3-C06', 'IKS-MSC-S3', 'Analiza e të dhënave të mëdha', 'ELECTIVE', 'IKS-MSC-S3-E1', 6.0, 2, 0, 2, 'dhurate-hyseni', 'jeta-dobruna', False, True),
    ('IKS-MSC-S3-C07', 'IKS-MSC-S3', 'Sisteme inteligjente multimediale', 'ELECTIVE', 'IKS-MSC-S3-E1', 6.0, 2, 0, 2, 'besmir-sejdiu', 'yllka-kabashi', False, True),
    ('IKS-MSC-S3-C08', 'IKS-MSC-S3', 'Modelet e mëdha gjuhësorë', 'ELECTIVE', 'IKS-MSC-S3-E1', 6.0, 2, 0, 2, 'kadri-sylejmani', 'mihrije-kadriu', False, True),
    ('IKS-MSC-S3-C09', 'IKS-MSC-S3', 'Menaxhimi i burimeve njerëzorë', 'ELECTIVE', 'IKS-MSC-S3-E2', 6.0, 2, 0, 2, 'nora-sadiku-dushi', 'blend-arifaj', False, True),
    ('IKS-MSC-S3-C10', 'IKS-MSC-S3', 'Menaxhimi strategjik', 'ELECTIVE', 'IKS-MSC-S3-E2', 6.0, 2, 0, 2, 'nora-sadiku-dushi', 'labeat-arbneshi', False, True),
    ('IKS-MSC-S4-C01', 'IKS-MSC-S4', 'Punimi i diplomës', 'MANDATORY', None, 30.0, 0, 0, 0, 'departamenti-fiek', 'jeta-dobruna', False, False),
    ('TIK-BSC-S1-C01', 'TIK-BSC-S1', 'Algjebra lineare me Kalkulus 1', 'MANDATORY', None, 7.0, 3, 3, 0, 'qefsere-doko', 'mergim-hoti', False, True),
    ('TIK-BSC-S1-C02', 'TIK-BSC-S1', 'Fizika inxhinierike 1', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S1-C03', 'TIK-BSC-S1', 'Bazat e inxhinierisë elektrike 1', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'doruntine-berisha', False, True),
    ('TIK-BSC-S1-C04', 'TIK-BSC-S1', 'Bazat e programimit', 'MANDATORY', None, 5.0, 2, 0, 2, 'avni-rexhepi', 'jeta-dobruna', False, True),
    ('TIK-BSC-S1-C05', 'TIK-BSC-S1', 'Shkathtësitë e komunikimit', 'MANDATORY', None, 3.0, 2, 0, 0, 'blerim-rexha', 'mergim-hoti', False, True),
    ('TIK-BSC-S1-C06', 'TIK-BSC-S1', 'Praktikumi në matematikë', 'ELECTIVE', 'TIK-BSC-S1-E1', 3.0, 2, 0, 0, 'departamenti-fiek', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S1-C07', 'TIK-BSC-S1', 'Veglat bazë softuerike', 'ELECTIVE', 'TIK-BSC-S1-E1', 3.0, 2, 0, 0, 'besmir-sejdiu', 'doruntine-berisha', False, True),
    ('TIK-BSC-S2-C01', 'TIK-BSC-S2', 'Gjeometri analitike me Kalkulus 2', 'MANDATORY', None, 7.0, 3, 3, 0, 'qefsere-doko', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S2-C02', 'TIK-BSC-S2', 'Fizika inxhinierike 2', 'MANDATORY', None, 5.0, 2, 1, 1, 'valon-veliu', 'doruntine-berisha', False, True),
    ('TIK-BSC-S2-C03', 'TIK-BSC-S2', 'Bazat e inxhinierisë elektrike 2', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'jeta-dobruna', False, True),
    ('TIK-BSC-S2-C04', 'TIK-BSC-S2', 'Algoritmet dhe strukturat e të dhënave', 'MANDATORY', None, 6.0, 2, 0, 2, 'kadri-sylejmani', 'mergim-hoti', False, True),
    ('TIK-BSC-S2-C05', 'TIK-BSC-S2', 'Qarqet digjitale', 'MANDATORY', None, 6.0, 2, 1, 1, 'sabrije-osmanaj', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S3-C01', 'TIK-BSC-S3', 'Probabilitet dhe statistikë', 'MANDATORY', None, 7.0, 3, 1, 0, 'valdete-rexhebeqaj-hamiti', 'doruntine-berisha', False, True),
    ('TIK-BSC-S3-C02', 'TIK-BSC-S3', 'Sinjalet dhe Informacioni', 'MANDATORY', None, 6.0, 3, 2, 0, 'enver-hamiti', 'jeta-dobruna', False, True),
    ('TIK-BSC-S3-C03', 'TIK-BSC-S3', 'Elektronika për TIK', 'MANDATORY', None, 6.0, 2, 0, 2, 'milaim-zabeli', 'mergim-hoti', False, True),
    ('TIK-BSC-S3-C04', 'TIK-BSC-S3', 'Teknologjitë e Internetit', 'MANDATORY', None, 6.0, 2, 0, 2, 'mimoza-ibrani', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S3-C05', 'TIK-BSC-S3', 'Veglat softuerike per Inxhinieri (Matlab, Python, etj.)', 'MANDATORY', None, 5.0, 2, 0, 2, 'bujar-krasniqi', 'doruntine-berisha', False, True),
    ('TIK-BSC-S4-C01', 'TIK-BSC-S4', 'Komunikimet digjitale', 'MANDATORY', None, 6.0, 3, 1, 1, 'enver-hamiti', 'jeta-dobruna', True, True),
    ('TIK-BSC-S4-C02', 'TIK-BSC-S4', 'Valët elektromagnetike', 'MANDATORY', None, 6.0, 2, 1, 1, 'mimoza-ibrani', 'mergim-hoti', True, True),
    ('TIK-BSC-S4-C03', 'TIK-BSC-S4', 'Transmetimi i të dhënave', 'MANDATORY', None, 5.0, 2, 0, 2, 'bujar-krasniqi', 'labeat-arbneshi', True, True),
    ('TIK-BSC-S4-C04', 'TIK-BSC-S4', 'Rrjetet komunikuese', 'MANDATORY', None, 5.0, 2, 0, 2, 'mimoza-ibrani', 'doruntine-berisha', True, True),
    ('TIK-BSC-S4-C05', 'TIK-BSC-S4', 'Praktika', 'MANDATORY', None, 3.0, 1, 0, 0, 'departamenti-fiek', 'jeta-dobruna', False, False),
    ('TIK-BSC-S4-C06', 'TIK-BSC-S4', 'Menaxhimi i projekteve', 'ELECTIVE', 'TIK-BSC-S4-E1', 5.0, 2, 1, 0, 'nora-sadiku-dushi', 'mergim-hoti', True, True),
    ('TIK-BSC-S4-C07', 'TIK-BSC-S4', 'Komunikime profesionale në anglisht', 'ELECTIVE', 'TIK-BSC-S4-E1', 5.0, 2, 1, 0, 'departamenti-fiek', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S4-C08', 'TIK-BSC-S4', 'Digitalizimi dhe inovacioni për zhvillim të qëndrueshëm', 'ELECTIVE', 'TIK-BSC-S4-E1', 5.0, 2, 1, 0, 'bujar-krasniqi', 'doruntine-berisha', False, True),
    ('TIK-BSC-S4-C09', 'TIK-BSC-S4', 'Etika në shkencë dhe inxhinieri', 'ELECTIVE', 'TIK-BSC-S4-E1', 5.0, 2, 1, 0, 'partneret-industrise', 'jeta-dobruna', False, True),
    ('TIK-BSC-S5-C01', 'TIK-BSC-S5', 'Projekte ne rrjete dhe komunikime', 'MANDATORY', None, 6.0, 2, 0, 1, 'mimoza-ibrani', 'mergim-hoti', False, True),
    ('TIK-BSC-S5-C02', 'TIK-BSC-S5', 'Internet of things', 'MANDATORY', None, 5.0, 3, 0, 2, 'bujar-krasniqi', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S5-C03', 'TIK-BSC-S5', 'Programimi për rrjete', 'MANDATORY', None, 6.0, 2, 0, 2, 'zana-limani-fazliu', 'doruntine-berisha', False, True),
    ('TIK-BSC-S5-C04', 'TIK-BSC-S5', 'Procesimi i sinjaleve dhe sistemet', 'MANDATORY', None, 5.0, 2, 0, 2, 'hena-maloku-berzati', 'jeta-dobruna', False, True),
    ('TIK-BSC-S5-C05', 'TIK-BSC-S5', 'Praktikë', 'MANDATORY', None, 3.0, 1, 0, 0, 'departamenti-fiek', 'mergim-hoti', False, False),
    ('TIK-BSC-S5-C06', 'TIK-BSC-S5', 'Web application development', 'ELECTIVE', 'TIK-BSC-S5-E1', 5.0, 2, 0, 2, 'zana-limani-fazliu', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S5-C07', 'TIK-BSC-S5', 'Teknologjitë dhe sistemet multimediale', 'ELECTIVE', 'TIK-BSC-S5-E1', 5.0, 2, 0, 2, 'hena-maloku-berzati', 'doruntine-berisha', False, True),
    ('TIK-BSC-S5-C08', 'TIK-BSC-S5', 'Cloud networking and big data', 'ELECTIVE', 'TIK-BSC-S5-E1', 5.0, 2, 0, 1, 'partneret-industrise', 'jeta-dobruna', False, True),
    ('TIK-BSC-S5-C09', 'TIK-BSC-S5', 'Ndërmarrësia dhe Inovacioni', 'ELECTIVE', 'TIK-BSC-S5-E1', 5.0, 2, 0, 1, 'nora-sadiku-dushi', 'mergim-hoti', False, True),
    ('TIK-BSC-S6-C01', 'TIK-BSC-S6', 'Inxhinieria e RF dhe Mikrovalëve', 'MANDATORY', None, 6.0, 2, 1, 1, 'enver-hamiti', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S6-C02', 'TIK-BSC-S6', 'Komunikimet Mobile', 'MANDATORY', None, 6.0, 2, 0, 1, 'hena-maloku-berzati', 'doruntine-berisha', False, True),
    ('TIK-BSC-S6-C03', 'TIK-BSC-S6', 'Inteligjenca artificiale dhe metodat e aplikuara', 'MANDATORY', None, 6.0, 3, 0, 1, 'zana-limani-fazliu', 'jeta-dobruna', False, True),
    ('TIK-BSC-S6-C04', 'TIK-BSC-S6', 'Projekti përfundimtar dhe praktika profesionale', 'MANDATORY', None, 8.0, 1, 0, 2, 'partneret-industrise', 'mergim-hoti', False, False),
    ('TIK-BSC-S6-C05', 'TIK-BSC-S6', 'Komunikimet e sigurta', 'ELECTIVE', 'TIK-BSC-S6-E1', 4.0, 2, 0, 1, 'zana-limani-fazliu', 'labeat-arbneshi', False, True),
    ('TIK-BSC-S6-C06', 'TIK-BSC-S6', 'Komunikimet Optike', 'ELECTIVE', 'TIK-BSC-S6-E1', 4.0, 2, 0, 1, 'bujar-krasniqi', 'doruntine-berisha', False, True),
    ('TIK-BSC-S6-C07', 'TIK-BSC-S6', 'Kapituj te përzgjedhur nga komunikimet', 'ELECTIVE', 'TIK-BSC-S6-E1', 4.0, 2, 0, 1, 'mimoza-ibrani', 'jeta-dobruna', False, True),
    ('TIK-BSC-S6-C08', 'TIK-BSC-S6', 'Animacioni dhe realiteti virtual', 'ELECTIVE', 'TIK-BSC-S6-E1', 4.0, 2, 0, 1, 'hena-maloku-berzati', 'mergim-hoti', False, True),
    ('TIK-MSC-S1-C01', 'TIK-MSC-S1', 'Planifikimi dhe optimizimi i rrjeteve', 'MANDATORY', None, 6.0, 3, 0, 1, 'bujar-krasniqi', 'mergim-hoti', False, True),
    ('TIK-MSC-S1-C02', 'TIK-MSC-S1', 'Perpunimi digjital i aplikuar', 'MANDATORY', None, 6.0, 3, 0, 1, 'hena-maloku-berzati', 'labeat-arbneshi', False, True),
    ('TIK-MSC-S1-C03', 'TIK-MSC-S1', 'Komunikimet pa tela 1', 'MANDATORY', None, 6.0, 3, 0, 1, 'mimoza-ibrani', 'doruntine-berisha', False, True),
    ('TIK-MSC-S1-C04', 'TIK-MSC-S1', 'Teoria e informacionit dhe kodimi', 'MANDATORY', None, 6.0, 3, 0, 1, 'zana-limani-fazliu', 'jeta-dobruna', False, True),
    ('TIK-MSC-S1-C05', 'TIK-MSC-S1', 'Metodologjia e Kërkimit Shkencor në TIK', 'MANDATORY', None, 6.0, 3, 0, 1, 'departamenti-fiek', 'mergim-hoti', False, True),
    ('TIK-MSC-S2-C01', 'TIK-MSC-S2', 'Rrjetat e avancuara dhe performanca e tyre', 'MANDATORY', None, 6.0, 3, 0, 1, 'hena-maloku-berzati', 'labeat-arbneshi', True, True),
    ('TIK-MSC-S2-C02', 'TIK-MSC-S2', 'Komunikimet pa tela II', 'MANDATORY', None, 6.0, 3, 0, 1, 'enver-hamiti', 'doruntine-berisha', True, True),
    ('TIK-MSC-S2-C03', 'TIK-MSC-S2', 'Të mësuarit makinerik në rrjeta komunikuese', 'MANDATORY', None, 6.0, 3, 0, 1, 'zana-limani-fazliu', 'jeta-dobruna', True, True),
    ('TIK-MSC-S2-C04', 'TIK-MSC-S2', 'Komunikimet pa tela -LAB', 'ELECTIVE', 'TIK-MSC-S2-E4', 6.0, 2, 0, 1, 'zana-limani-fazliu', 'mergim-hoti', True, True),
    ('TIK-MSC-S2-C05', 'TIK-MSC-S2', 'Laboratori i Rrjetave të Avancuara Komunikuese', 'ELECTIVE', 'TIK-MSC-S2-E4', 6.0, 2, 0, 1, 'departamenti-fiek', 'labeat-arbneshi', False, True),
    ('TIK-MSC-S2-C06', 'TIK-MSC-S2', 'Programim i avancuar për TIK', 'ELECTIVE', 'TIK-MSC-S2-E4', 6.0, 2, 0, 1, 'zana-limani-fazliu', 'doruntine-berisha', False, True),
    ('TIK-MSC-S2-C07', 'TIK-MSC-S2', 'Përpunimi i imazheve dhe vizioni kompjuterik', 'ELECTIVE', 'TIK-MSC-S2-E4', 6.0, 2, 0, 1, 'hena-maloku-berzati', 'jeta-dobruna', False, True),
    ('TIK-MSC-S2-C08', 'TIK-MSC-S2', 'Menaxhimi i avancuar i projekteve në TIK', 'ELECTIVE', 'TIK-MSC-S2-E5', 6.0, 2, 0, 0, 'partneret-industrise', 'mergim-hoti', True, True),
    ('TIK-MSC-S2-C09', 'TIK-MSC-S2', 'Rregullimi dhe standardizimi në TIK', 'ELECTIVE', 'TIK-MSC-S2-E5', 6.0, 2, 0, 0, 'bujar-krasniqi', 'labeat-arbneshi', False, True),
    ('TIK-MSC-S3-C01', 'TIK-MSC-S3', 'Siguria e rrjeteve dhe komunikimeve', 'MANDATORY', None, 6.0, 2, 0, 1, 'bujar-krasniqi', 'doruntine-berisha', False, True),
    ('TIK-MSC-S3-C02', 'TIK-MSC-S3', 'Praktika', 'MANDATORY', None, 6.0, 1, 0, 0, 'departamenti-fiek', 'jeta-dobruna', False, False),
    ('TIK-MSC-S3-C03', 'TIK-MSC-S3', 'SDR dhe rrjetet kognitive', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'hena-maloku-berzati', 'mergim-hoti', False, True),
    ('TIK-MSC-S3-C04', 'TIK-MSC-S3', 'Komunikimet vehikulare', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'hena-maloku-berzati', 'labeat-arbneshi', False, True),
    ('TIK-MSC-S3-C05', 'TIK-MSC-S3', 'Kapituj te zgjedhur ne komunikime multimediale', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'hena-maloku-berzati', 'doruntine-berisha', False, True),
    ('TIK-MSC-S3-C06', 'TIK-MSC-S3', 'Kapituj te vecante ne komunikime dhe rrjeta', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'mimoza-ibrani', 'jeta-dobruna', False, True),
    ('TIK-MSC-S3-C07', 'TIK-MSC-S3', 'Komunikimet me vale milimetrike', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'departamenti-fiek', 'mergim-hoti', False, True),
    ('TIK-MSC-S3-C08', 'TIK-MSC-S3', 'Komunikimet Satelitore', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'departamenti-fiek', 'labeat-arbneshi', False, True),
    ('TIK-MSC-S3-C09', 'TIK-MSC-S3', 'Sistemet mikrovalore', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'enver-hamiti', 'doruntine-berisha', False, True),
    ('TIK-MSC-S3-C10', 'TIK-MSC-S3', 'Komunikimet e avancuara optike', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'partneret-industrise', 'jeta-dobruna', False, True),
    ('TIK-MSC-S3-C11', 'TIK-MSC-S3', 'Inovacioni dhe transferi i teknologjise', 'ELECTIVE', 'TIK-MSC-S3-E1', 6.0, 2, 0, 2, 'partneret-industrise', 'mergim-hoti', False, True),
    ('TIK-MSC-S4-C01', 'TIK-MSC-S4', 'Tema e Masterit', 'MANDATORY', None, 30.0, 0, 0, 0, 'departamenti-fiek', 'jeta-dobruna', False, False),
]

ELECTIVE_GROUP_SPECS = [
    ('EAR-BSC-S1-E1', 'EAR-BSC-S1', 'EAR-BSC S1 - grupi zgjedhor E1', 1),
    ('EAR-BSC-S5-E1', 'EAR-BSC-S5', 'EAR-BSC S5 - grupi zgjedhor E1', 1),
    ('EAR-BSC-S6-E1', 'EAR-BSC-S6', 'EAR-BSC S6 - grupi zgjedhor E1', 1),
    ('EAR-MSC-S1-E1', 'EAR-MSC-S1', 'EAR-MSC S1 - grupi zgjedhor E1', 2),
    ('EAR-MSC-S2-E1', 'EAR-MSC-S2', 'EAR-MSC S2 - grupi zgjedhor E1', 2),
    ('EAR-MSC-S3-E1', 'EAR-MSC-S3', 'EAR-MSC S3 - grupi zgjedhor E1', 2),
    ('EE-BSC-S1-E1', 'EE-BSC-S1', 'EE-BSC S1 - grupi zgjedhor E1', 1),
    ('EE-BSC-S3-E1', 'EE-BSC-S3', 'EE-BSC S3 - grupi zgjedhor E1', 1),
    ('EE-BSC-S4-E1', 'EE-BSC-S4', 'EE-BSC S4 - grupi zgjedhor E1', 1),
    ('EE-BSC-S5-E1', 'EE-BSC-S5', 'EE-BSC S5 - grupi zgjedhor E1', 1),
    ('EE-BSC-S6-E5', 'EE-BSC-S6', 'EE-BSC S6 - grupi zgjedhor E5', 1),
    ('EE-BSC-S6-E6', 'EE-BSC-S6', 'EE-BSC S6 - grupi zgjedhor E6', 1),
    ('EE-MSC-S2-E4', 'EE-MSC-S2', 'EE-MSC S2 - grupi zgjedhor E4', 1),
    ('EE-MSC-S2-E5', 'EE-MSC-S2', 'EE-MSC S2 - grupi zgjedhor E5', 1),
    ('EE-MSC-S3-E4', 'EE-MSC-S3', 'EE-MSC S3 - grupi zgjedhor E4', 1),
    ('EE-MSC-S3-E5', 'EE-MSC-S3', 'EE-MSC S3 - grupi zgjedhor E5', 1),
    ('IKS-BSC-S1-E1', 'IKS-BSC-S1', 'IKS-BSC S1 - grupi zgjedhor E1', 1),
    ('IKS-BSC-S4-E1', 'IKS-BSC-S4', 'IKS-BSC S4 - grupi zgjedhor E1', 1),
    ('IKS-BSC-S5-E5', 'IKS-BSC-S5', 'IKS-BSC S5 - grupi zgjedhor E5', 1),
    ('IKS-BSC-S5-E6', 'IKS-BSC-S5', 'IKS-BSC S5 - grupi zgjedhor E6', 1),
    ('IKS-BSC-S6-E1', 'IKS-BSC-S6', 'IKS-BSC S6 - grupi zgjedhor E1', 1),
    ('IKS-MSC-S2-E1', 'IKS-MSC-S2', 'IKS-MSC S2 - grupi zgjedhor E1', 2),
    ('IKS-MSC-S3-E1', 'IKS-MSC-S3', 'IKS-MSC S3 - grupi zgjedhor E1', 1),
    ('IKS-MSC-S3-E2', 'IKS-MSC-S3', 'IKS-MSC S3 - grupi zgjedhor E2', 1),
    ('TIK-BSC-S1-E1', 'TIK-BSC-S1', 'TIK-BSC S1 - grupi zgjedhor E1', 1),
    ('TIK-BSC-S4-E1', 'TIK-BSC-S4', 'TIK-BSC S4 - grupi zgjedhor E1', 1),
    ('TIK-BSC-S5-E1', 'TIK-BSC-S5', 'TIK-BSC S5 - grupi zgjedhor E1', 1),
    ('TIK-BSC-S6-E1', 'TIK-BSC-S6', 'TIK-BSC S6 - grupi zgjedhor E1', 1),
    ('TIK-MSC-S2-E4', 'TIK-MSC-S2', 'TIK-MSC S2 - grupi zgjedhor E4', 1),
    ('TIK-MSC-S2-E5', 'TIK-MSC-S2', 'TIK-MSC S2 - grupi zgjedhor E5', 1),
    ('TIK-MSC-S3-E1', 'TIK-MSC-S3', 'TIK-MSC S3 - grupi zgjedhor E1', 1),
]

CO_LECTURERS = {'EAR-BSC-S1-C01': ('shqipe-lohaj', 'valdete-rexhebeqaj-hamiti'), 'EAR-BSC-S1-C02': (), 'EAR-BSC-S1-C03': ('mimoza-ibrani', 'vjosa-shatri'), 'EAR-BSC-S1-C04': ('kadri-sylejmani',), 'EAR-BSC-S1-C05': ('sabrije-osmanaj', 'bujar-krasniqi'), 'EAR-BSC-S1-C06': (), 'EAR-BSC-S1-C07': (), 'EAR-BSC-S2-C01': ('shqipe-lohaj', 'valdete-rexhebeqaj-hamiti'), 'EAR-BSC-S2-C02': (), 'EAR-BSC-S2-C03': ('mimoza-ibrani', 'vjosa-shatri'), 'EAR-BSC-S2-C04': ('avni-rexhepi',), 'EAR-BSC-S2-C05': ('artan-mazrekaj',), 'EAR-BSC-S3-C01': (), 'EAR-BSC-S3-C02': (), 'EAR-BSC-S3-C03': (), 'EAR-BSC-S3-C04': (), 'EAR-BSC-S3-C05': (), 'EAR-BSC-S3-C06': (), 'EAR-BSC-S4-C01': (), 'EAR-BSC-S4-C02': ('arben-gjukaj',), 'EAR-BSC-S4-C03': (), 'EAR-BSC-S4-C04': (), 'EAR-BSC-S4-C05': ('dhurate-hyseni',), 'EAR-BSC-S4-C06': (), 'EAR-BSC-S5-C01': (), 'EAR-BSC-S5-C02': (), 'EAR-BSC-S5-C03': (), 'EAR-BSC-S5-C04': (), 'EAR-BSC-S5-C05': (), 'EAR-BSC-S5-C06': (), 'EAR-BSC-S5-C07': (), 'EAR-BSC-S5-C08': (), 'EAR-BSC-S5-C09': (), 'EAR-BSC-S5-C10': (), 'EAR-BSC-S5-C11': (), 'EAR-BSC-S5-C12': (), 'EAR-BSC-S5-C13': (), 'EAR-BSC-S5-C14': (), 'EAR-BSC-S5-C15': (), 'EAR-BSC-S5-C16': (), 'EAR-BSC-S5-C17': (), 'EAR-BSC-S5-C18': (), 'EAR-BSC-S6-C01': (), 'EAR-BSC-S6-C02': (), 'EAR-BSC-S6-C03': (), 'EAR-BSC-S6-C04': (), 'EAR-BSC-S6-C05': (), 'EAR-BSC-S6-C06': (), 'EAR-BSC-S6-C07': (), 'EAR-BSC-S6-C08': (), 'EAR-BSC-S6-C09': (), 'EAR-BSC-S6-C10': (), 'EAR-BSC-S6-C11': (), 'EAR-BSC-S6-C12': (), 'EAR-BSC-S6-C13': (), 'EAR-BSC-S6-C14': (), 'EAR-BSC-S6-C15': (), 'EAR-BSC-S6-C16': (), 'EAR-BSC-S6-C17': (), 'EAR-MSC-S1-C01': (), 'EAR-MSC-S1-C02': (), 'EAR-MSC-S1-C03': (), 'EAR-MSC-S1-C04': (), 'EAR-MSC-S1-C05': (), 'EAR-MSC-S1-C06': (), 'EAR-MSC-S1-C07': (), 'EAR-MSC-S1-C08': (), 'EAR-MSC-S1-C09': (), 'EAR-MSC-S1-C10': (), 'EAR-MSC-S2-C01': (), 'EAR-MSC-S2-C02': (), 'EAR-MSC-S2-C03': (), 'EAR-MSC-S2-C04': (), 'EAR-MSC-S2-C05': (), 'EAR-MSC-S2-C06': (), 'EAR-MSC-S2-C07': (), 'EAR-MSC-S2-C08': (), 'EAR-MSC-S2-C09': (), 'EAR-MSC-S2-C10': (), 'EAR-MSC-S3-C01': (), 'EAR-MSC-S3-C02': (), 'EAR-MSC-S3-C03': (), 'EAR-MSC-S3-C04': (), 'EAR-MSC-S3-C05': (), 'EAR-MSC-S3-C06': (), 'EAR-MSC-S3-C07': (), 'EAR-MSC-S3-C08': (), 'EAR-MSC-S3-C09': (), 'EAR-MSC-S3-C10': ('nuri-berisha',), 'EAR-MSC-S3-C11': (), 'EAR-MSC-S4-C01': (), 'EE-BSC-S1-C01': (), 'EE-BSC-S1-C02': ('enver-hamiti', 'mimoza-ibrani'), 'EE-BSC-S1-C03': ('kadri-sylejmani',), 'EE-BSC-S1-C04': ('sabrije-osmanaj', 'bujar-krasniqi'), 'EE-BSC-S1-C05': (), 'EE-BSC-S1-C06': (), 'EE-BSC-S1-C07': ('valdete-rexhebeqaj-hamiti',), 'EE-BSC-S2-C01': (), 'EE-BSC-S2-C02': ('enver-hamiti',), 'EE-BSC-S2-C03': ('kadri-sylejmani', 'avni-rexhepi'), 'EE-BSC-S2-C04': ('artan-mazrekaj',), 'EE-BSC-S2-C05': ('valdete-rexhebeqaj-hamiti',), 'EE-BSC-S3-C01': (), 'EE-BSC-S3-C02': (), 'EE-BSC-S3-C03': (), 'EE-BSC-S3-C04': (), 'EE-BSC-S3-C05': ('drilon-bunjaku',), 'EE-BSC-S3-C06': (), 'EE-BSC-S3-C07': (), 'EE-BSC-S3-C08': (), 'EE-BSC-S3-C09': (), 'EE-BSC-S4-C01': (), 'EE-BSC-S4-C02': (), 'EE-BSC-S4-C03': (), 'EE-BSC-S4-C04': (), 'EE-BSC-S4-C05': (), 'EE-BSC-S4-C06': (), 'EE-BSC-S4-C07': (), 'EE-BSC-S4-C08': (), 'EE-BSC-S5-C01': (), 'EE-BSC-S5-C02': (), 'EE-BSC-S5-C03': (), 'EE-BSC-S5-C04': (), 'EE-BSC-S5-C05': (), 'EE-BSC-S5-C06': (), 'EE-BSC-S5-C07': (), 'EE-BSC-S5-C08': (), 'EE-BSC-S5-C09': (), 'EE-BSC-S6-C01': (), 'EE-BSC-S6-C02': (), 'EE-BSC-S6-C03': (), 'EE-BSC-S6-C04': (), 'EE-BSC-S6-C05': (), 'EE-BSC-S6-C06': (), 'EE-BSC-S6-C07': (), 'EE-BSC-S6-C08': (), 'EE-BSC-S6-C09': (), 'EE-BSC-S6-C10': (), 'EE-MSC-S1-C01': (), 'EE-MSC-S1-C02': (), 'EE-MSC-S1-C03': (), 'EE-MSC-S1-C04': (), 'EE-MSC-S1-C05': (), 'EE-MSC-S2-C01': (), 'EE-MSC-S2-C02': ('drilon-bunjaku',), 'EE-MSC-S2-C03': (), 'EE-MSC-S2-C04': (), 'EE-MSC-S2-C05': (), 'EE-MSC-S2-C06': ('shqipe-lohaj',), 'EE-MSC-S2-C07': (), 'EE-MSC-S2-C08': (), 'EE-MSC-S2-C09': (), 'EE-MSC-S2-C10': (), 'EE-MSC-S3-C01': (), 'EE-MSC-S3-C02': (), 'EE-MSC-S3-C03': (), 'EE-MSC-S3-C04': (), 'EE-MSC-S3-C05': (), 'EE-MSC-S3-C06': (), 'EE-MSC-S3-C07': (), 'EE-MSC-S3-C08': (), 'EE-MSC-S3-C09': (), 'EE-MSC-S3-C10': (), 'EE-MSC-S4-C01': (), 'IKS-BSC-S1-C01': ('shqipe-lohaj', 'valdete-rexhebeqaj-hamiti'), 'IKS-BSC-S1-C02': (), 'IKS-BSC-S1-C03': ('mimoza-ibrani', 'vjosa-shatri'), 'IKS-BSC-S1-C04': ('kadri-sylejmani',), 'IKS-BSC-S1-C05': ('sabrije-osmanaj', 'bujar-krasniqi'), 'IKS-BSC-S1-C06': (), 'IKS-BSC-S1-C07': (), 'IKS-BSC-S2-C01': ('shqipe-lohaj', 'valdete-rexhebeqaj-hamiti'), 'IKS-BSC-S2-C02': (), 'IKS-BSC-S2-C03': ('mimoza-ibrani', 'vjosa-shatri'), 'IKS-BSC-S2-C04': ('avni-rexhepi',), 'IKS-BSC-S2-C05': ('artan-mazrekaj',), 'IKS-BSC-S3-C01': (), 'IKS-BSC-S3-C02': ('milaim-zabeli',), 'IKS-BSC-S3-C03': (), 'IKS-BSC-S3-C04': (), 'IKS-BSC-S3-C05': (), 'IKS-BSC-S3-C06': (), 'IKS-BSC-S4-C01': (), 'IKS-BSC-S4-C02': (), 'IKS-BSC-S4-C03': (), 'IKS-BSC-S4-C04': (), 'IKS-BSC-S4-C05': (), 'IKS-BSC-S4-C06': (), 'IKS-BSC-S4-C07': (), 'IKS-BSC-S5-C01': (), 'IKS-BSC-S5-C02': (), 'IKS-BSC-S5-C03': (), 'IKS-BSC-S5-C04': (), 'IKS-BSC-S5-C05': (), 'IKS-BSC-S5-C06': (), 'IKS-BSC-S5-C07': (), 'IKS-BSC-S5-C08': (), 'IKS-BSC-S5-C09': (), 'IKS-BSC-S5-C10': (), 'IKS-BSC-S5-C11': (), 'IKS-BSC-S6-C01': (), 'IKS-BSC-S6-C02': (), 'IKS-BSC-S6-C03': (), 'IKS-BSC-S6-C04': (), 'IKS-BSC-S6-C05': (), 'IKS-BSC-S6-C06': (), 'IKS-BSC-S6-C07': (), 'IKS-BSC-S6-C08': (), 'IKS-BSC-S6-C09': (), 'IKS-BSC-S6-C10': (), 'IKS-BSC-S6-C11': (), 'IKS-BSC-S6-C12': (), 'IKS-BSC-S6-C13': (), 'IKS-BSC-S6-C14': (), 'IKS-BSC-S6-C15': (), 'IKS-BSC-S6-C16': (), 'IKS-MSC-S1-C01': (), 'IKS-MSC-S1-C02': (), 'IKS-MSC-S1-C03': (), 'IKS-MSC-S1-C04': (), 'IKS-MSC-S1-C05': (), 'IKS-MSC-S2-C01': (), 'IKS-MSC-S2-C02': (), 'IKS-MSC-S2-C03': (), 'IKS-MSC-S2-C04': (), 'IKS-MSC-S2-C05': (), 'IKS-MSC-S2-C06': (), 'IKS-MSC-S3-C01': (), 'IKS-MSC-S3-C02': (), 'IKS-MSC-S3-C03': (), 'IKS-MSC-S3-C04': (), 'IKS-MSC-S3-C05': (), 'IKS-MSC-S3-C06': (), 'IKS-MSC-S3-C07': (), 'IKS-MSC-S3-C08': (), 'IKS-MSC-S3-C09': (), 'IKS-MSC-S3-C10': (), 'IKS-MSC-S4-C01': (), 'TIK-BSC-S1-C01': ('shqipe-lohaj', 'valdete-rexhebeqaj-hamiti'), 'TIK-BSC-S1-C02': (), 'TIK-BSC-S1-C03': ('mimoza-ibrani', 'vjosa-shatri'), 'TIK-BSC-S1-C04': ('kadri-sylejmani',), 'TIK-BSC-S1-C05': ('sabrije-osmanaj', 'bujar-krasniqi'), 'TIK-BSC-S1-C06': (), 'TIK-BSC-S1-C07': (), 'TIK-BSC-S2-C01': ('shqipe-lohaj', 'valdete-rexhebeqaj-hamiti'), 'TIK-BSC-S2-C02': (), 'TIK-BSC-S2-C03': ('mimoza-ibrani', 'vjosa-shatri'), 'TIK-BSC-S2-C04': ('avni-rexhepi',), 'TIK-BSC-S2-C05': ('artan-mazrekaj',), 'TIK-BSC-S3-C01': (), 'TIK-BSC-S3-C02': (), 'TIK-BSC-S3-C03': (), 'TIK-BSC-S3-C04': (), 'TIK-BSC-S3-C05': (), 'TIK-BSC-S4-C01': (), 'TIK-BSC-S4-C02': (), 'TIK-BSC-S4-C03': (), 'TIK-BSC-S4-C04': (), 'TIK-BSC-S4-C05': (), 'TIK-BSC-S4-C06': (), 'TIK-BSC-S4-C07': (), 'TIK-BSC-S4-C08': (), 'TIK-BSC-S4-C09': (), 'TIK-BSC-S5-C01': (), 'TIK-BSC-S5-C02': (), 'TIK-BSC-S5-C03': (), 'TIK-BSC-S5-C04': (), 'TIK-BSC-S5-C05': (), 'TIK-BSC-S5-C06': (), 'TIK-BSC-S5-C07': (), 'TIK-BSC-S5-C08': (), 'TIK-BSC-S5-C09': (), 'TIK-BSC-S6-C01': (), 'TIK-BSC-S6-C02': (), 'TIK-BSC-S6-C03': (), 'TIK-BSC-S6-C04': (), 'TIK-BSC-S6-C05': (), 'TIK-BSC-S6-C06': (), 'TIK-BSC-S6-C07': (), 'TIK-BSC-S6-C08': (), 'TIK-MSC-S1-C01': (), 'TIK-MSC-S1-C02': (), 'TIK-MSC-S1-C03': (), 'TIK-MSC-S1-C04': (), 'TIK-MSC-S1-C05': (), 'TIK-MSC-S2-C01': ('mimoza-ibrani',), 'TIK-MSC-S2-C02': (), 'TIK-MSC-S2-C03': (), 'TIK-MSC-S2-C04': (), 'TIK-MSC-S2-C05': (), 'TIK-MSC-S2-C06': (), 'TIK-MSC-S2-C07': (), 'TIK-MSC-S2-C08': (), 'TIK-MSC-S2-C09': (), 'TIK-MSC-S3-C01': (), 'TIK-MSC-S3-C02': (), 'TIK-MSC-S3-C03': ('zana-limani-fazliu',), 'TIK-MSC-S3-C04': ('zana-limani-fazliu',), 'TIK-MSC-S3-C05': (), 'TIK-MSC-S3-C06': (), 'TIK-MSC-S3-C07': (), 'TIK-MSC-S3-C08': (), 'TIK-MSC-S3-C09': (), 'TIK-MSC-S3-C10': (), 'TIK-MSC-S3-C11': (), 'TIK-MSC-S4-C01': ()}

ACTIVE_PROGRAMS = {'IKS-BSC-S4': 90, 'EAR-BSC-S4': 70, 'TIK-BSC-S4': 70, 'EE-BSC-S4': 60, 'IKS-MSC-S2': 35, 'EAR-MSC-S2': 30, 'TIK-MSC-S2': 25, 'EE-MSC-S2': 30}
