"""create staff groups and rooms

Revision ID: 077bc9fa0904
Revises: 5be5dcd6f5f1
Create Date: 2026-08-25 13:39:15.147794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077bc9fa0904'
down_revision: Union[str, Sequence[str], None] = '5be5dcd6f5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('GENERAL_ROOM', 'LABORATORY', name='room_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='room_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.CheckConstraint('capacity > 0', name='capacity_positive'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'code', name='uq_rooms_faculty_code')
    )
    op.create_table('staff_members',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('academic_title', sa.Enum('FULL_PROFESSOR', 'ASSOCIATE_PROFESSOR', 'ASSISTANT_PROFESSOR', 'ASSISTANT', 'OTHER', name='academic_title'), nullable=True),
    sa.Column('staff_type', sa.Enum('INTERNAL', 'ENGAGED', 'OTHER_UP_FACULTY', 'EXTERNAL', name='staff_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_staff_members_email')
    )
    op.create_table('program_room_preferences',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('study_program_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('penalty_weight', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('penalty_weight >= 0', name='penalty_weight_nonnegative'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_program_id', 'room_id', name='uq_program_room_preferences_program_room')
    )
    op.create_table('room_availability',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('availability_type', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'PREFERRED', 'AVOID', name='availability_type'), nullable=False),
    sa.Column('preference_weight', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='day_of_week_valid'),
    sa.CheckConstraint('end_time > start_time', name='valid_time_range'),
    sa.CheckConstraint('preference_weight IS NULL OR preference_weight >= 0', name='preference_weight_nonnegative'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'academic_term_id', 'day_of_week', 'start_time', 'end_time', 'availability_type', name='uq_room_availability_window')
    )
    op.create_table('staff_availability',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('availability_type', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'PREFERRED', 'AVOID', name='availability_type'), nullable=False),
    sa.Column('preference_weight', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='day_of_week_valid'),
    sa.CheckConstraint('end_time > start_time', name='valid_time_range'),
    sa.CheckConstraint('preference_weight IS NULL OR preference_weight >= 0', name='preference_weight_nonnegative'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_courses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('can_lecture', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_assist', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('can_lecture = true OR can_assist = true', name='teaching_capability_required'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_member_id', 'course_id', name='uq_staff_courses_staff_course')
    )
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('program_semester_id', sa.Integer(), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_type', sa.Enum('COHORT', 'LECTURE_GROUP', 'NUMERICAL_GROUP', 'LAB_GROUP', name='student_group_type'), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('parent_group_id IS NULL OR parent_group_id <> id', name='parent_group_not_self'),
    sa.CheckConstraint('student_count > 0', name='student_count_positive'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['parent_group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['program_semester_id'], ['program_semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_semester_id', 'academic_term_id', 'name', name='uq_student_groups_semester_term_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_groups')
    op.drop_table('staff_courses')
    op.drop_table('staff_availability')
    op.drop_table('room_availability')
    op.drop_table('program_room_preferences')
    op.drop_table('staff_members')
    op.drop_table('rooms')
    # ### end Alembic commands ###
