"""create academic structure

Revision ID: 5be5dcd6f5f1
Revises: a89e3281be40
Create Date: 2026-08-24 20:16:11.590088

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be5dcd6f5f1'
down_revision: str | Sequence[str] | None = 'a89e3281be40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='valid_date_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_academic_years_name')
    )
    op.create_index('uq_current_academic_year', 'academic_years', ['is_current'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('courses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_courses_code')
    )
    op.create_table('academic_terms',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('term_type', sa.Enum('WINTER', 'SUMMER', name='term_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='valid_date_range'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'term_type', name='uq_academic_terms_year_type')
    )
    op.create_table('study_programs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'level_id', 'code', name='uq_study_programs_faculty_level_code')
    )
    op.create_table('program_semesters',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('study_program_id', sa.Integer(), nullable=False),
    sa.Column('semester_number', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('semester_number > 0', name='semester_number_positive'),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_program_id', 'semester_number', name='uq_program_semesters_program_number')
    )
    op.create_table('elective_groups',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('program_semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('required_choices', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('required_choices > 0', name='required_choices_positive'),
    sa.ForeignKeyConstraint(['program_semester_id'], ['program_semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_semester_id', 'name', name='uq_elective_groups_semester_name')
    )
    op.create_table('curriculum_courses',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('program_semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.Enum('MANDATORY', 'ELECTIVE', name='course_type'), nullable=False),
    sa.Column('elective_group_id', sa.Integer(), nullable=True),
    sa.Column('ects', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('lecture_periods_per_week', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('numerical_periods_per_week', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('laboratory_periods_per_week', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('(lecture_periods_per_week + numerical_periods_per_week + laboratory_periods_per_week) > 0', name='weekly_periods_positive'),
    sa.CheckConstraint('ects > 0', name='ects_positive'),
    sa.CheckConstraint('laboratory_periods_per_week >= 0', name='laboratory_periods_nonnegative'),
    sa.CheckConstraint('lecture_periods_per_week >= 0', name='lecture_periods_nonnegative'),
    sa.CheckConstraint('numerical_periods_per_week >= 0', name='numerical_periods_nonnegative'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['elective_group_id'], ['elective_groups.id'], ),
    sa.ForeignKeyConstraint(['program_semester_id'], ['program_semesters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_semester_id', 'course_id', name='uq_curriculum_courses_semester_course')
    )
    op.alter_column('faculties', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('faculties_name_key'), 'faculties', type_='unique')
    op.drop_index(op.f('ix_faculties_code'), table_name='faculties')
    op.create_unique_constraint('uq_faculties_code', 'faculties', ['code'])
    op.drop_column('faculties', 'created_at')
    op.alter_column('levels', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('levels', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('levels', 'semester_count',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_levels_code'), table_name='levels')
    op.drop_constraint(op.f('levels_name_key'), 'levels', type_='unique')
    op.create_unique_constraint('uq_levels_code', 'levels', ['code'])
    op.drop_column('levels', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_levels_code', 'levels', type_='unique')
    op.create_unique_constraint(op.f('levels_name_key'), 'levels', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_levels_code'), 'levels', ['code'], unique=True)
    op.alter_column('levels', 'semester_count',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('levels', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('levels', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.add_column('faculties', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_faculties_code', 'faculties', type_='unique')
    op.create_index(op.f('ix_faculties_code'), 'faculties', ['code'], unique=True)
    op.create_unique_constraint(op.f('faculties_name_key'), 'faculties', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('faculties', 'code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_table('curriculum_courses')
    op.drop_table('elective_groups')
    op.drop_table('program_semesters')
    op.drop_table('study_programs')
    op.drop_table('academic_terms')
    op.drop_table('courses')
    op.drop_index('uq_current_academic_year', table_name='academic_years', postgresql_where=sa.text('is_current = true'))
    op.drop_table('academic_years')
    # ### end Alembic commands ###
