"""create scheduling inputs

Revision ID: 7bed9014bad0
Revises: 077bc9fa0904
Create Date: 2026-08-25 14:12:34.857121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bed9014bad0'
down_revision: Union[str, Sequence[str], None] = '077bc9fa0904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_profiles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slot_minutes', sa.SmallInteger(), server_default=sa.text('45'), nullable=False),
    sa.Column('max_lecture_students', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('max_numerical_students', sa.Integer(), server_default=sa.text('40'), nullable=False),
    sa.Column('max_lab_students', sa.Integer(), server_default=sa.text('40'), nullable=False),
    sa.Column('preferred_room_weight', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('historical_room_weight', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('student_gap_weight', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('staff_gap_weight', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('late_hour_weight', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('historical_room_weight >= 0', name='historical_room_weight_nonnegative'),
    sa.CheckConstraint('late_hour_weight >= 0', name='late_hour_weight_nonnegative'),
    sa.CheckConstraint('max_lab_students > 0', name='max_lab_students_positive'),
    sa.CheckConstraint('max_lecture_students > 0', name='max_lecture_students_positive'),
    sa.CheckConstraint('max_numerical_students > 0', name='max_numerical_students_positive'),
    sa.CheckConstraint('preferred_room_weight >= 0', name='preferred_room_weight_nonnegative'),
    sa.CheckConstraint('slot_minutes > 0', name='slot_minutes_positive'),
    sa.CheckConstraint('staff_gap_weight >= 0', name='staff_gap_weight_nonnegative'),
    sa.CheckConstraint('student_gap_weight >= 0', name='student_gap_weight_nonnegative'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'name', name='uq_scheduling_profiles_faculty_name')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('scheduling_profile_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('slot_index', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='day_of_week_valid'),
    sa.CheckConstraint('end_time > start_time', name='valid_time_range'),
    sa.CheckConstraint('slot_index >= 0', name='slot_index_nonnegative'),
    sa.ForeignKeyConstraint(['scheduling_profile_id'], ['scheduling_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduling_profile_id', 'day_of_week', 'slot_index', name='uq_time_slots_profile_day_index'),
    sa.UniqueConstraint('scheduling_profile_id', 'day_of_week', 'start_time', name='uq_time_slots_profile_day_start')
    )
    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('curriculum_course_id', sa.Integer(), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('expected_students', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'CANCELLED', 'COMPLETED', name='course_offering_status'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.CheckConstraint('expected_students IS NULL OR expected_students > 0', name='expected_students_positive'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['curriculum_course_id'], ['curriculum_courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_course_id', 'academic_term_id', name='uq_course_offerings_curriculum_term')
    )
    op.create_table('course_sessions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('component_type', sa.Enum('LECTURE', 'NUMERICAL', 'LABORATORY', name='component_type'), nullable=False),
    sa.Column('weekly_frequency', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('duration_slots', sa.SmallInteger(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('required_room_type', postgresql.ENUM('GENERAL_ROOM', 'LABORATORY', name='room_type', create_type=False,), nullable=True),
    sa.Column('required_room_id', sa.Integer(), nullable=True),
    sa.Column('is_splittable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('duration_slots > 0', name='duration_slots_positive'),
    sa.CheckConstraint('max_students IS NULL OR max_students > 0', name='max_students_positive'),
    sa.CheckConstraint('weekly_frequency > 0', name='weekly_frequency_positive'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ),
    sa.ForeignKeyConstraint(['required_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_offering_id', 'name', name='uq_course_sessions_offering_name')
    )
    op.create_table('course_session_dependencies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('predecessor_session_id', sa.Integer(), nullable=False),
    sa.Column('successor_session_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.Enum('PRECEDES', 'SAME_DAY', 'DIFFERENT_DAY', 'CONSECUTIVE', name='dependency_type'), nullable=False),
    sa.Column('min_gap_slots', sa.SmallInteger(), nullable=True),
    sa.Column('max_gap_slots', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('max_gap_slots IS NULL OR max_gap_slots >= 0', name='max_gap_slots_nonnegative'),
    sa.CheckConstraint('min_gap_slots IS NULL OR max_gap_slots IS NULL OR max_gap_slots >= min_gap_slots', name='gap_range_valid'),
    sa.CheckConstraint('min_gap_slots IS NULL OR min_gap_slots >= 0', name='min_gap_slots_nonnegative'),
    sa.CheckConstraint('predecessor_session_id <> successor_session_id', name='sessions_must_differ'),
    sa.ForeignKeyConstraint(['predecessor_session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['successor_session_id'], ['course_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_session_id', 'successor_session_id', 'dependency_type', name='uq_course_session_dependencies_pair_type')
    )
    op.create_table('course_session_groups',
    sa.Column('course_session_id', sa.Integer(), nullable=False),
    sa.Column('student_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], ),
    sa.PrimaryKeyConstraint('course_session_id', 'student_group_id')
    )
    op.create_table('course_session_staff',
    sa.Column('course_session_id', sa.Integer(), nullable=False),
    sa.Column('staff_member_id', sa.Integer(), nullable=False),
    sa.Column('teaching_role', sa.Enum('LECTURER', 'NUMERICAL_INSTRUCTOR', 'LAB_INSTRUCTOR', name='teaching_role'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['course_session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ),
    sa.PrimaryKeyConstraint('course_session_id', 'staff_member_id')
    )
    op.create_table('course_session_time_constraints',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('course_session_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('constraint_type', sa.Enum('ALLOWED_WINDOW', 'FORBIDDEN_WINDOW', 'PREFERRED_WINDOW', 'FIXED_WINDOW', name='time_constraint_type'), nullable=False),
    sa.Column('preference_weight', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('day_of_week IS NULL OR day_of_week BETWEEN 1 AND 7', name='day_of_week_valid'),
    sa.CheckConstraint('end_time > start_time', name='valid_time_range'),
    sa.CheckConstraint('preference_weight IS NULL OR preference_weight >= 0', name='preference_weight_nonnegative'),
    sa.ForeignKeyConstraint(['course_session_id'], ['course_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_session_time_constraints')
    op.drop_table('course_session_staff')
    op.drop_table('course_session_groups')
    op.drop_table('course_session_dependencies')
    op.drop_table('course_sessions')
    op.drop_table('course_offerings')
    op.drop_table('time_slots')
    op.drop_table('scheduling_profiles')
    # ### end Alembic commands ###
