"""create timetable runs and entries

Revision ID: e6c979861d02
Revises: 7bed9014bad0
Create Date: 2026-08-25 16:32:32.132830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6c979861d02'
down_revision: Union[str, Sequence[str], None] = '7bed9014bad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_runs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('academic_term_id', sa.Integer(), nullable=False),
    sa.Column('scheduling_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.Enum('GENERATED', 'MANUAL', 'IMPORTED', 'REOPTIMIZED', name='timetable_source_type'), nullable=False),
    sa.Column('algorithm', sa.Enum('FIRST_FIT_DECREASING', 'BEST_FIT_DECREASING', 'CP_SAT', 'HYBRID', name='scheduling_algorithm'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'INFEASIBLE', 'FAILED', 'CANCELLED', name='timetable_run_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('objective_score', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('hard_conflicts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('soft_penalty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('execution_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('execution_time_ms IS NULL OR execution_time_ms >= 0', name='execution_time_ms_nonnegative'),
    sa.CheckConstraint('hard_conflicts >= 0', name='hard_conflicts_nonnegative'),
    sa.CheckConstraint('soft_penalty IS NULL OR soft_penalty >= 0', name='soft_penalty_nonnegative'),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_terms.id'], ),
    sa.ForeignKeyConstraint(['scheduling_profile_id'], ['scheduling_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_term_id', 'scheduling_profile_id', 'name', name='uq_timetable_runs_term_profile_name')
    )
    op.create_index('uq_published_timetable', 'timetable_runs', ['academic_term_id', 'scheduling_profile_id'], unique=True, postgresql_where=sa.text('is_published = true'))
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('timetable_run_id', sa.Integer(), nullable=False),
    sa.Column('course_session_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_number', sa.SmallInteger(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_slot_id', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('assignment_source', sa.Enum('SOLVER', 'MANUAL', 'IMPORTED', 'PRESERVED', name='assignment_source'), server_default=sa.text("'SOLVER'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('occurrence_number > 0', name='occurrence_number_positive'),
    sa.ForeignKeyConstraint(['course_session_id'], ['course_sessions.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['start_slot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['timetable_run_id'], ['timetable_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_run_id', 'course_session_id', 'occurrence_number', name='uq_timetable_entries_run_session_occurrence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_entries')
    op.drop_index('uq_published_timetable', table_name='timetable_runs', postgresql_where=sa.text('is_published = true'))
    op.drop_table('timetable_runs')
    # ### end Alembic commands ###
