"""default lab group limit to 20

Revision ID: e785b8054ab9
Revises: 149fee23c191
Create Date: 2026-09-08 15:13:12.318237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e785b8054ab9'
down_revision: Union[str, Sequence[str], None] = '149fee23c191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduling_profiles', 'max_lab_students',
               existing_type=sa.INTEGER(),
               server_default=sa.text('20'),
               existing_nullable=False)
    op.execute(
        sa.text(
            """
            UPDATE scheduling_profiles
            SET max_lab_students = 20
            WHERE name = 'FIEK - orari standard 45 minuta'
              AND max_lab_students = 40
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduling_profiles', 'max_lab_students',
               existing_type=sa.INTEGER(),
               server_default=sa.text('40'),
               existing_nullable=False)
    # ### end Alembic commands ###
