from app.core.exception_handlers import register_exception_handlers
from app.core.exceptions import (
    AppError,
    AuthenticationError,
    AvailabilityConflictError,
    BusinessRuleError,
    ConflictError,
    DataImportError,
    DependencyCycleError,
    DuplicateResourceError,
    GroupHierarchyError,
    InactiveResourceError,
    InvalidReferenceError,
    InvalidStateTransitionError,
    LockedEntryError,
    PermissionDeniedError,
    PersistenceError,
    ResourceInUseError,
    ResourceNotFoundError,
    RoomCompatibilityError,
    SchedulingInfeasibleError,
    SchedulingInputError,
    SlotContinuityError,
    SolverExecutionError,
    StaffQualificationError,
    TimetableConflictError,
    TimetablePublishError,
)


__all__ = [
    "AppError",
    "AuthenticationError",
    "AvailabilityConflictError",
    "BusinessRuleError",
    "ConflictError",
    "DataImportError",
    "DependencyCycleError",
    "DuplicateResourceError",
    "GroupHierarchyError",
    "InactiveResourceError",
    "InvalidReferenceError",
    "InvalidStateTransitionError",
    "LockedEntryError",
    "PermissionDeniedError",
    "PersistenceError",
    "ResourceInUseError",
    "ResourceNotFoundError",
    "RoomCompatibilityError",
    "SchedulingInfeasibleError",
    "SchedulingInputError",
    "SlotContinuityError",
    "SolverExecutionError",
    "StaffQualificationError",
    "TimetableConflictError",
    "TimetablePublishError",
    "register_exception_handlers",
]
